import type { SubjectAnalytics, SkillAnalytics } from "./analytics";
import type { BadgeDefinition } from "./gamification";
import type { SubjectConfidence } from "./adaptiveDifficulty";
import type { CompetencyParentSummary } from "./ali/parentSummary";

export type ExamReadiness = "not-ready" | "building" | "nearly-ready" | "exam-ready";

export interface ParentInsight {
  id: string;
  text: string;
  type: "positive" | "attention" | "action";
}

export interface FocusArea {
  label: string;
  href: string;
  detail: string;
  frequency: string;
}

export interface ParentReport {
  xp: number;
  rank: string;
  streak: number;
  totalSessions: number;
  weeklySessions: number;
  overallScore: number;
  estimatedMinutes: number;
  examReadiness: ExamReadiness;
  subjects: SubjectAnalytics[];
  skills: SkillAnalytics[];
  parentInsights: ParentInsight[];
  focusAreas: FocusArea[];
  earnedBadges: BadgeDefinition[];
  weeklyXP: number;
  hasEnoughData: boolean;
  subjectConfidence: SubjectConfidence[];
  // Competency-first summaries (Phase ALI 1.4) — one entry per subject with
  // real ALI data. Empty array when no subject has any (fallback: existing
  // parentInsights/focusAreas below are the only Parent Insights content,
  // exactly as before this phase).
  competencySummaries: CompetencyParentSummary[];

  // ─── Work Package WP-12 (Implementation Programme, AIW-001 §9) ───────

  /**
   * Competency codes with a real DurableMasteryRecord (WP-07,
   * lib/ali/durableMastery.ts) where `durable === true`. Empty array today
   * — no live DurableMasteryRecord table exists yet (WP-07 built the pure
   * evaluation logic, not the persistence layer), so this is honestly
   * empty rather than fabricated, ready to populate once one does.
   */
  durablyMastered: string[];
  /**
   * Plain-language "why this recommendation" text, generated by WP-10's
   * generateExplanation(candidate, "parent") from a real
   * RecommendationCandidate (WP-09). Undefined when no live recommendation
   * exists to explain — never populated with placeholder text.
   */
  recommendationExplanation?: string;
  /**
   * Deliberately coarse, qualitative signal (AEP-005 §13) — never a
   * numeric score. Null today: no real Wellbeing computation exists
   * anywhere in this codebase yet (the same honest gap WP-09's Tier 0
   * flagged) — this field exists so the shape is ready to receive a real
   * signal once one is designed, not to imply one has been computed.
   */
  wellbeingSignal: "steady" | "may benefit from a lighter week" | null;
}
