import { Lightbulb } from "lucide-react";
import { InfoCard } from "@/components/ui/Card";
import type { RecommendationRuntimeResult } from "@/lib/ali/persistence/recommendationRuntime";

/**
 * "What's Next" (Sprint 2, ANGEL-CSSE-002A Deliverables 3 & 5 — Recommendation
 * Engine Integration + Parent Visibility). Renders the "parent" audience text
 * from lib/ali/explainability.ts's generateExplanation() — real,
 * confidence-calibrated, evidence-based reasoning already generated by
 * getRecommendations(), not new copy written for this component. Only the
 * top few ordered candidates are shown (already tiered/ranked by
 * orchestrateRecommendations()); wellbeing-vetoed competencies are skipped
 * entirely, per the veto's own intent. The same call also generates
 * "learner"/"engineering-audit" text — deliberately not rendered here,
 * out of this sprint's scoped surface.
 */
export function RecommendationExplanation({
  result,
  maxItems = 3,
}: {
  result: RecommendationRuntimeResult;
  maxItems?: number;
}) {
  const visible = result.ordered
    .filter((candidate) => !result.vetoedCompetencyCodes.includes(candidate.competencyCode))
    .slice(0, maxItems);

  if (visible.length === 0) {
    return (
      <p className="text-sm text-gray-400 dark:text-gray-500 italic">
        Nothing to suggest right now — check back as your child completes more practice.
      </p>
    );
  }

  return (
    <div className="space-y-2">
      {visible.map((candidate) => {
        const parentExplanation = result.explanations
          .get(candidate.competencyCode)
          ?.find((e) => e.audience === "parent");
        if (!parentExplanation) return null;

        return (
          <InfoCard key={candidate.competencyCode} className="flex items-start gap-3">
            <Lightbulb size={16} className="text-purple-500 mt-0.5 shrink-0" />
            <p className="text-sm text-gray-700 dark:text-gray-300">{parentExplanation.text}</p>
          </InfoCard>
        );
      })}
    </div>
  );
}
