import type { RecommendationRuntimeResult } from "@/lib/ali/persistence/recommendationRuntime";

/**
 * "What's Next" (Sprint 2, ANGEL-CSSE-002A Deliverables 3 & 5 — Recommendation
 * Engine Integration + Parent Visibility). Renders the "parent" audience text
 * from lib/ali/explainability.ts's generateExplanation() — real,
 * confidence-calibrated, evidence-based reasoning already generated by
 * getRecommendations(), not new copy written for this component. Only the
 * top few ordered candidates are shown (already tiered/ranked by
 * orchestrateRecommendations()); wellbeing-vetoed competencies are skipped
 * entirely, per the veto's own intent. The same call also generates
 * "learner"/"engineering-audit" text — deliberately not rendered here,
 * out of this sprint's scoped surface.
 */
export function RecommendationExplanation({
  result,
  maxItems = 3,
}: {
  result: RecommendationRuntimeResult;
  maxItems?: number;
}) {
  const visible = result.ordered
    .filter((candidate) => !result.vetoedCompetencyCodes.includes(candidate.competencyCode))
    .slice(0, maxItems);

  if (visible.length === 0) {
    return (
      <p className="text-sm text-[var(--angel-muted)] italic">
        Nothing to suggest right now. Check back as your child completes more practice.
      </p>
    );
  }

  return (
    <div className="bg-[var(--angel-paper)] border border-[var(--angel-border)] rounded-lg divide-y divide-[var(--angel-border)]">
      {visible.map((candidate) => {
        const parentExplanation = result.explanations
          .get(candidate.competencyCode)
          ?.find((e) => e.audience === "parent");
        if (!parentExplanation) return null;

        return (
          <p key={candidate.competencyCode} className="text-sm text-[var(--angel-ink)] p-5">
            {parentExplanation.text}
          </p>
        );
      })}
    </div>
  );
}
