import type { BankQuestion } from "@/types/ali/questionBank";
import { buildExperiences, type ManifestValidationReport } from "./mockComposition";

/**
 * Mathematics First Mock — Founder Review Report (Decision 210 Part
 * 10, Decision 212). The smallest practical inspection surface the
 * governing directive asked for: a deterministic, human-readable text
 * report of a candidate composition, showing exactly what a learner
 * would receive (ordered numbered questions, grouped subparts, question
 * text, shared stems, stimuli, marks, difficulty, skills) plus the
 * composition's own totals and validation result. Pure function, no I/O
 * — a caller (a script, or a future admin route) is responsible for
 * displaying or persisting the returned string.
 *
 * Deliberately text, not a new admin UI page: the existing admin-beta
 * review surface (`app/admin-beta/review/page.tsx`) is built around
 * `ali_family_review`'s own per-family educational review workflow, a
 * genuinely different shape (one family at a time, decision recorded per
 * family) from "inspect one whole candidate paper before a single
 * freeze decision." Building a new, bespoke admin route for a capability
 * that does not yet have any real composed candidate to review would be
 * exactly the "large new administration product" the governing directive
 * explicitly warned against; this report is generated by
 * `scripts/mock-mathematics-composition-report.mjs` for direct Founder
 * reading today, and remains the natural first candidate for promotion
 * into a UI page in a future, separately-scoped increment if the Founder
 * wants richer interaction than a static report affords.
 */

function readPromptField(row: BankQuestion, field: string): unknown {
  const prompt = row.prompt as unknown as Record<string, unknown>;
  return prompt?.[field];
}

function questionText(row: BankQuestion): string {
  const q = readPromptField(row, "question");
  return typeof q === "string" ? q : "(no question text)";
}

function sharedStemOf(row: BankQuestion): string | null {
  const s = readPromptField(row, "sharedStem");
  return typeof s === "string" && s.length > 0 ? s : null;
}

function stimulusOf(row: BankQuestion): unknown {
  return readPromptField(row, "stimulus");
}

function formatStimulus(stimulus: unknown): string | null {
  if (!stimulus || typeof stimulus !== "object") return null;
  const s = stimulus as { type?: unknown; caption?: unknown; headers?: unknown; rows?: unknown };
  if (s.type !== "table" || !Array.isArray(s.headers) || !Array.isArray(s.rows)) return null;
  const headerLine = `    | ${s.headers.join(" | ")} |`;
  const rowLines = s.rows.map((r) => `    | ${Array.isArray(r) ? r.join(" | ") : String(r)} |`);
  const caption = typeof s.caption === "string" ? `    (${s.caption})\n` : "";
  return `${caption}${headerLine}\n${rowLines.join("\n")}`;
}

export interface FounderReviewReportOptions {
  title: string;
  targetExperienceCount: number;
}

/**
 * Renders the full Founder-inspection report for one candidate manifest.
 * `manifestQuestionIds` is expected (but not required) to be the output
 * of `composeCandidateMock()`; `pool` must be the same candidate pool the
 * composition/validation was run against, so every id resolves. Any id
 * that fails to resolve is rendered as an explicit "(unresolved)" line
 * rather than silently skipped -- this report never hides a validation
 * problem from the Founder.
 */
export function renderFounderReviewReport(
  manifestQuestionIds: readonly string[],
  pool: readonly BankQuestion[],
  report: ManifestValidationReport,
  options: FounderReviewReportOptions
): string {
  const byId = new Map(pool.map((q) => [q.id, q]));
  const includedRows = manifestQuestionIds.map((id) => byId.get(id)).filter((r): r is BankQuestion => r !== undefined);
  const experiences = buildExperiences(includedRows);

  const lines: string[] = [];
  lines.push(`=== ${options.title} ===`);
  lines.push(`Target numbered questions: ${options.targetExperienceCount}`);
  lines.push(`Validation: ${report.valid ? "VALID" : "INVALID"}`);
  if (!report.valid) {
    lines.push(`Validation failures (${report.failures.length}):`);
    for (const f of report.failures) lines.push(`  - [${f.code}] ${f.detail}`);
  }
  lines.push(`Numbered-question count: ${report.numberedQuestionCount}`);
  lines.push(`Raw row count: ${report.rawRowCount}`);
  lines.push(`Total marks: ${report.totalMarks}`);
  lines.push(
    `Difficulty distribution: easy=${report.difficultyDistribution.easy} medium=${report.difficultyDistribution.medium} hard=${report.difficultyDistribution.hard} challenge=${report.difficultyDistribution.challenge}`
  );
  lines.push(`Skill/archetype distribution: ${Object.entries(report.skillDistribution).map(([k, v]) => `${k}=${v}`).join(", ") || "(none)"}`);
  lines.push(`Family IDs represented: ${report.familyIds.join(", ") || "(none)"}`);
  lines.push("");
  lines.push("--- Ordered numbered questions (what a learner would see) ---");

  experiences.forEach((exp, index) => {
    const rows = exp.questionIds.map((id) => byId.get(id)).filter((r): r is BankQuestion => r !== undefined);
    if (rows.length === 0) {
      lines.push(`${index + 1}. (unresolved -- ${exp.experienceId})`);
      return;
    }
    const stem = exp.isGrouped ? sharedStemOf(rows[0]) : null;
    lines.push(`${index + 1}. [${exp.experienceId}] marks=${exp.marks} difficulty=${exp.contentDifficulties.join("/")} skill=${exp.skills.join(",")}`);
    if (stem) lines.push(`   Shared stem: ${stem}`);
    // One stimulus per display unit (Decision 170's own convention, see
    // selectDisplayUnitStimulus in lib/mockAttempt/workspace.ts) -- the
    // first row in the group that actually carries a valid one, not
    // necessarily the group's own first row.
    const stimulusRow = rows.find((r) => formatStimulus(stimulusOf(r)) !== null);
    const stimulus = stimulusRow ? formatStimulus(stimulusOf(stimulusRow)) : null;
    if (stimulus) {
      lines.push(`   Stimulus:`);
      lines.push(stimulus);
    }
    for (const row of rows) {
      const label = row.subpartLabel ? ` ${row.subpartLabel}` : "";
      const text = questionText(row);
      const tail = stem && text.startsWith(stem) ? text.slice(stem.length).trimStart() : text;
      lines.push(`   ${label ? label.trim() : ""} ${tail}`.trimStart());
    }
  });

  return lines.join("\n");
}
