-- Angel Digital 11+ — Migration 016
-- Educational Identity Registration — Phase 2C, Batch 1 (English + Maths)
-- Generated by scripts/educational-identity-registration.ts — deterministic,
-- idempotent (on conflict do nothing, matching migration 013's own pattern).
-- Every id below reuses the item's existing data/*.ts id verbatim — no new
-- identity minted. Every skill/competency mapping is disclosed with its
-- reasoning in EDUCATIONAL_IDENTITY_BATCH1_RECONCILIATION.md.
-- Additive-only. Depends on migrations 005, 007, 013. Does not modify any
-- existing row.
-- Run this in: Supabase Dashboard > SQL Editor > New query

insert into public.ali_question_bank
  (id, subject, skill, pathway, content_difficulty, question_type, estimated_time_seconds, prompt, explanation, mastery_threshold, learning_unit_id)
values

('eng-001-q1', 'english', 'QT-RC-05', array['csse'], 'medium', 'short-answer', 90,
 $json${
  "id": "eng-001-q1",
  "question": "What atmosphere does the writer create in the opening paragraph? Use evidence from the text to support your answer.",
  "skill": "atmosphere",
  "marks": 3,
  "hint": "Think about the weather, the setting, and the word choices.",
  "modelAnswer": "The writer creates an atmosphere of tension and unease. The phrase 'wind whipped' suggests a harsh, threatening environment, while 'the keeper had vanished' introduces mystery and danger. The lighthouse light is described as 'indifferent', suggesting that nature and machinery carry on despite the human drama — which makes the situation feel more isolated and chilling.",
  "passageTitle": "The Lighthouse Mystery",
  "passageText": "The wind whipped across the harbour as Mira pressed herself against the cold stone wall of the lighthouse. Three weeks had passed since the keeper had vanished, and still no explanation had emerged. The light continued to sweep the dark water in its steady, mechanical arc, indifferent to the mystery it illuminated.\n\nShe had found the notebook wedged behind a loose brick on the second landing — its pages dense with cramped handwriting, each entry growing more frantic than the last. The final entry simply read: \"It knows I'm here.\"\n\nAbove her, the great lens hummed and revolved. Somewhere below, the sea answered with its patient, ancient rhythm. Mira turned the notebook over in her hands. Whatever had happened here, the lighthouse held its secrets close."
}$json$,
 'Open interpretive question requiring evidence (''use evidence from the text'') to support a judgement about atmosphere — same shape as eng-002-q1 (already tagged QT-RC-05, competency RC-02): asks what something reveals, supported by cited evidence, not a single quoted phrase''s effect.', 2, 'eng-001'),

('eng-001-q4', 'english', 'QT-RC-10', array['csse'], 'medium', 'short-answer', 90,
 $json${
  "id": "eng-001-q4",
  "question": "Why do you think the writer chose to make the final journal entry so short? What effect does this create?",
  "skill": "inference",
  "marks": 3,
  "hint": "Compare the final entry to what came before it. What does brevity suggest?",
  "modelAnswer": "The writer uses contrast: the earlier entries are described as 'dense with cramped handwriting', but the final entry is only six words. This abruptness creates shock and dread — the keeper either had no time to write more, or was interrupted. The short sentence 'It knows I'm here' is more frightening because it is so direct and unexplained. The reader's imagination fills in what 'it' might be.",
  "passageTitle": "The Lighthouse Mystery",
  "passageText": "The wind whipped across the harbour as Mira pressed herself against the cold stone wall of the lighthouse. Three weeks had passed since the keeper had vanished, and still no explanation had emerged. The light continued to sweep the dark water in its steady, mechanical arc, indifferent to the mystery it illuminated.\n\nShe had found the notebook wedged behind a loose brick on the second landing — its pages dense with cramped handwriting, each entry growing more frantic than the last. The final entry simply read: \"It knows I'm here.\"\n\nAbove her, the great lens hummed and revolved. Somewhere below, the sea answered with its patient, ancient rhythm. Mira turned the notebook over in her hands. Whatever had happened here, the lighthouse held its secrets close."
}$json$,
 'Asks ''why did the writer choose X, what effect does this create'' about a specific stylistic choice (entry brevity) — same shape as eng-001-q3 (already tagged QT-RC-10, competency RC-02): an explicit effect-of-technique question, not a general evidence-based inference.', 2, 'eng-001'),

('eng-003-q1', 'english', 'QT-RC-05', array['csse'], 'hard', 'short-answer', 120,
 $json${
  "id": "eng-003-q1",
  "question": "What does Thomas mean when he says he 'no longer recognises the young man who left Coventry in September'? What has changed?",
  "skill": "inference",
  "marks": 4,
  "hint": "Look at the whole letter — what does he say about himself, the men, and his plans? What does this reveal?",
  "modelAnswer": "Thomas means that the experience of war has transformed him — he has grown up quickly and changed fundamentally. He describes discovering 'a resolve I did not know I possessed', suggesting he has found inner strength he was unaware of before. He looks forward to ordinary things — sawdust and woodwork — with 'greater appreciation', showing he now values what he previously took for granted. War has made him more mature, reflective and grateful.",
  "passageTitle": "Letters from the Trenches",
  "passageText": "My dear mother,\n\nI am writing this in what passes for a quiet hour, though I use the word 'quiet' loosely. The guns are never entirely still, and one learns, in time, to hear them as a kind of weather — threatening but distant, like a storm that may or may not arrive.\n\nWe have been here three weeks now and I confess I no longer recognise the young man who left Coventry in September. I do not say this to worry you. I have found here a kind of resolve I did not know I possessed. The men beside me are extraordinary — ordinary men made extraordinary by circumstance.\n\nTell Father I am well. Tell him also that I have been thinking much about the workshop, and that when this business is finished, I intend to return to it with a greater appreciation for the smell of sawdust and the sound of wood being worked than I ever had before.\n\nThe stars here are remarkable, mother. I suspect they are the same stars you see above Coventry, but they look different from here — older and further away. I take comfort in knowing we share them.\n\nYour loving son,\nThomas"
}$json$,
 'Gives a direct quotation (''no longer recognises the young man...'') and asks for its meaning plus what has changed — Quotation-and-Explanation, matching eng-002-q1''s tagged pattern (QT-RC-05, competency RC-02). Not QT-RC-03 (Word/Phrase Meaning): the quoted unit is a full clause with follow-on interpretation, not a single word/phrase gloss.', 3, 'eng-003'),

('qa-001', 'maths', 'QT-MR-01', array['csse'], 'medium', 'short-answer', 60,
 $json${
  "id": "qa-001",
  "question": "847 + 356 = ?",
  "answer": "1203",
  "skill": "arithmetic",
  "difficulty": "year5-core",
  "marks": 1
}$json$,
 'Direct arithmetic computation (847 + 356) — same shape as mth-002/mth-008/qa-008, already tagged QT-MR-01, competency MR-01.', 2, 'qa-001'),

('qa-002', 'maths', 'QT-MR-01', array['csse'], 'medium', 'short-answer', 60,
 $json${
  "id": "qa-002",
  "question": "1000 - 473 = ?",
  "answer": "527",
  "skill": "arithmetic",
  "difficulty": "year5-core",
  "marks": 1
}$json$,
 'Direct arithmetic computation (1000 - 473) — QT-MR-01, competency MR-01.', 2, 'qa-002'),

('qa-003', 'maths', 'QT-MR-01', array['csse'], 'medium', 'short-answer', 60,
 $json${
  "id": "qa-003",
  "question": "24 × 35 = ?",
  "answer": "840",
  "skill": "arithmetic",
  "difficulty": "year5-core",
  "marks": 1
}$json$,
 'Direct arithmetic computation (24 x 35) — QT-MR-01, competency MR-01.', 2, 'qa-003'),

('qa-004', 'maths', 'QT-MR-01', array['csse'], 'medium', 'short-answer', 60,
 $json${
  "id": "qa-004",
  "question": "756 ÷ 9 = ?",
  "answer": "84",
  "skill": "arithmetic",
  "difficulty": "year5-core",
  "marks": 1
}$json$,
 'Direct arithmetic computation (756 / 9) — QT-MR-01, competency MR-01.', 2, 'qa-004'),

('qa-005', 'maths', 'QT-MR-01', array['csse'], 'medium', 'short-answer', 60,
 $json${
  "id": "qa-005",
  "question": "12.5 × 8 = ?",
  "answer": "100",
  "skill": "arithmetic",
  "difficulty": "year5-core",
  "marks": 1
}$json$,
 'Direct arithmetic computation (12.5 x 8) — QT-MR-01, competency MR-01.', 2, 'qa-005'),

('qa-006', 'maths', 'QT-MR-01', array['csse'], 'medium', 'short-answer', 60,
 $json${
  "id": "qa-006",
  "question": "3/4 of 240 = ?",
  "answer": "180",
  "skill": "fractions",
  "difficulty": "year5-core",
  "marks": 1
}$json$,
 'Fraction-of-quantity calculation (3/4 of 240). Reuses mth-004''s own disclosed precedent exactly: fractions fold into Assessment Brain''s Arithmetic Calculation domain since no dedicated fractions Question Type exists — QT-MR-01, competency MR-01.', 2, 'qa-006'),

('qa-007', 'maths', 'QT-MR-04', array['csse'], 'medium', 'short-answer', 60,
 $json${
  "id": "qa-007",
  "question": "15% of 60 = ?",
  "answer": "9",
  "skill": "arithmetic",
  "difficulty": "year5-core",
  "marks": 1
}$json$,
 'Percentage-of-a-number calculation (15% of 60). Unlike fractions, Assessment Brain has a dedicated Question Type for this (QT-MR-04, Percentage/Proportional Change) — matches mth-010''s precedent exactly, not QT-MR-01.', 2, 'qa-007'),

('qa-009', 'maths', 'QT-MR-01', array['csse'], 'medium', 'short-answer', 60,
 $json${
  "id": "qa-009",
  "question": "2³ × 5 = ?",
  "answer": "40",
  "skill": "arithmetic",
  "difficulty": "year5-core",
  "marks": 1
}$json$,
 'Direct arithmetic computation (2^3 x 5) — same shape as mth-002''s power calculation, QT-MR-01, competency MR-01.', 2, 'qa-009')

on conflict (id) do nothing;
