-- Angel Digital 11+ — Migration 018
-- Educational Identity Registration — Phase 2C, Batch 3 (Verbal / Non-Verbal / Spatial / Numerical Reasoning)
-- Generated by scripts/educational-identity-registration.ts — deterministic,
-- idempotent (on conflict do nothing, matching migration 013's own pattern).
-- Every id below reuses the item's existing data/*.ts id verbatim — no new
-- identity minted. Every skill/competency mapping is disclosed with its
-- reasoning in EDUCATIONAL_IDENTITY_PHASE2C_FINAL_REPORT.md.
-- Additive-only. Depends on migrations 005, 007, 013. Does not modify any
-- existing row.
-- Run this in: Supabase Dashboard > SQL Editor > New query

-- NO ROWS THIS BATCH. Every item scanned for Batch 3 (Verbal / Non-Verbal / Spatial / Numerical Reasoning) was classified
-- 'requires-review' (no evidence-supported Question Type mapping exists) —
-- see EDUCATIONAL_IDENTITY_PHASE2C_FINAL_REPORT.md for the per-item reasoning. This file is
-- intentionally a no-op, kept in the migration sequence as a real, honest
-- record that this batch was processed and found nothing safe to register,
-- not skipped.
select 1; -- intentional no-op, see comment above
