-- Angel Digital 11+ — Migration 031
-- Educational Increment 004: CSSE Mathematics Content Scale Wave 1.
--
-- 29 new Mathematics items across 5 families, 3 competencies (MR-02, MR-03,
-- MR-05), all deterministically generated by
-- scripts/generate-mathematics-wave1.mjs — every answer is computed in
-- code from the item's own parameters, never hand-typed alongside a
-- hand-typed question, and validated for duplicate id/question/(non-binary)
-- answer before this file was written (node scripts/generate-mathematics-wave1.mjs
-- reports PASS). Chosen per MATHEMATICS_COVERAGE_MATRIX_V1.md: MR-02 and
-- MR-03 are both EMC-4 (Established) and were the two most under-supplied
-- Established competencies (2 and 3 items respectively before this
-- migration); MR-05 has a real, evidenced QT-MR-11 archetype and had only
-- 1 item. MR-01 (already dominant) and MR-04/MR-06 (already recently
-- addressed) are deliberately not touched, per the Coverage Matrix's own
-- prioritisation rationale.
--
-- Families (grounded in docs/intelligence/CSSE_QUESTION_INTELLIGENCE_
-- FRAMEWORK.md, read before writing any generator, not assumed from a
-- competency name):
--   mr02-sequence-rule   (QT-MR-05) — function-rule application, forward
--                          + inverse (reverse-reasoning pair), 10 items
--   mr02-substitution    (QT-MR-06) — symbolic system, substitution + solve,
--                          5 items, difficulty 'hard' (genuinely multi-step)
--   mr03-angle-sum       (QT-MR-07) — angle-sum reasoning, triangle (4) +
--                          quadrilateral (3) sub-archetypes, 7 items
--   mr05-number-property (QT-MR-11) — true/false judgement sub-format
--                          (well-evidenced, 5 items) + a "search" sub-format
--                          reformulated to have one unambiguous answer
--                          rather than the evidenced-but-ambiguous "find a
--                          pair" task (2 items, explicitly disclosed as the
--                          LOW-confidence sub-format per the evidence
--                          record)
--
-- provenance = 'angel_original' throughout. eligibility_status =
-- 'practice_eligible' throughout, not higher — each item has a disclosed,
-- non-forced Question Type/competency mapping (the Provisional -> Practice
-- Eligible bar), but none has had the independent (non-author) review
-- RELEASE_1_ASSESSMENT_ELIGIBILITY_MODEL.md's next transition requires,
-- consistent with Educational Increment 003's own MR-06 items.
--
-- Every question text and explanation checked against the Copy Quality
-- Guard's rule (no em/en dash sentence punctuation) by hand before this
-- migration was written, since the guard itself cannot scan database
-- content.
--
-- ali_question_bank has no browser-writable RLS/grant path — this must be
-- applied via Supabase Dashboard > SQL Editor, the same as every other
-- content migration in this project; it cannot be applied from
-- application code or the anon key.

begin;

insert into public.ali_question_bank
  (id, subject, skill, pathway, content_difficulty, question_type, estimated_time_seconds,
   prompt, explanation, mastery_threshold, learning_unit_id,
   family_id, provenance, eligibility_status, content_version, active, addresses_misconception)
values

('mr02-seq-01-fwd', 'maths', 'QT-MR-05', array['csse'], 'easy', 'short-answer', 60,
 $json${"id":"mr02-seq-01-fwd","marks":1,"skill":"algebra","answer":"17","question":"A rule is: multiply by 3, then add 2. What is the output when the input is 5?","workingSteps":["5 × 3 = 15","15 + 2 = 17"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-05, competency MR-02. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q5/Q11/Q15 (2023), CSSE-011 Q7/Q8 (2022), CSSE-016 Q21 (2021).', 2, 'wave1-mr02-sequence-rule',
 'mr02-sequence-rule', 'angel_original', 'practice_eligible', 1, true, 'Forgetting to apply both steps (e.g. giving 15, the multiplication only, without adding 2).'),

('mr02-seq-01-inv', 'maths', 'QT-MR-05', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr02-seq-01-inv","marks":1,"skill":"algebra","answer":"7","question":"A rule is: multiply by 3, then add 2. The output is 23. What was the input?","workingSteps":["Reverse the rule: subtract 2 first, then divide by 3","23 - 2 = 21","21 ÷ 3 = 7"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-05, competency MR-02. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q5/Q11/Q15 (2023), CSSE-011 Q7/Q8 (2022), CSSE-016 Q21 (2021).', 2, 'wave1-mr02-sequence-rule',
 'mr02-sequence-rule', 'angel_original', 'practice_eligible', 1, true, 'Applying the rule forwards instead of reversing it (e.g. multiplying 23 by 3 instead of subtracting then dividing).'),

('mr02-seq-02-fwd', 'maths', 'QT-MR-05', array['csse'], 'easy', 'short-answer', 60,
 $json${"id":"mr02-seq-02-fwd","marks":1,"skill":"algebra","answer":"25","question":"A rule is: multiply by 4, then add 1. What is the output when the input is 6?","workingSteps":["6 × 4 = 24","24 + 1 = 25"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-05, competency MR-02. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q5/Q11/Q15 (2023), CSSE-011 Q7/Q8 (2022), CSSE-016 Q21 (2021).', 2, 'wave1-mr02-sequence-rule',
 'mr02-sequence-rule', 'angel_original', 'practice_eligible', 1, true, 'Forgetting to apply both steps (e.g. giving 24, the multiplication only, without adding 1).'),

('mr02-seq-02-inv', 'maths', 'QT-MR-05', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr02-seq-02-inv","marks":1,"skill":"algebra","answer":"8","question":"A rule is: multiply by 4, then add 1. The output is 33. What was the input?","workingSteps":["Reverse the rule: subtract 1 first, then divide by 4","33 - 1 = 32","32 ÷ 4 = 8"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-05, competency MR-02. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q5/Q11/Q15 (2023), CSSE-011 Q7/Q8 (2022), CSSE-016 Q21 (2021).', 2, 'wave1-mr02-sequence-rule',
 'mr02-sequence-rule', 'angel_original', 'practice_eligible', 1, true, 'Applying the rule forwards instead of reversing it (e.g. multiplying 33 by 4 instead of subtracting then dividing).'),

('mr02-seq-03-fwd', 'maths', 'QT-MR-05', array['csse'], 'easy', 'short-answer', 60,
 $json${"id":"mr02-seq-03-fwd","marks":1,"skill":"algebra","answer":"23","question":"A rule is: multiply by 2, then add 5. What is the output when the input is 9?","workingSteps":["9 × 2 = 18","18 + 5 = 23"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-05, competency MR-02. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q5/Q11/Q15 (2023), CSSE-011 Q7/Q8 (2022), CSSE-016 Q21 (2021).', 2, 'wave1-mr02-sequence-rule',
 'mr02-sequence-rule', 'angel_original', 'practice_eligible', 1, true, 'Forgetting to apply both steps (e.g. giving 18, the multiplication only, without adding 5).'),

('mr02-seq-03-inv', 'maths', 'QT-MR-05', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr02-seq-03-inv","marks":1,"skill":"algebra","answer":"13","question":"A rule is: multiply by 2, then add 5. The output is 31. What was the input?","workingSteps":["Reverse the rule: subtract 5 first, then divide by 2","31 - 5 = 26","26 ÷ 2 = 13"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-05, competency MR-02. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q5/Q11/Q15 (2023), CSSE-011 Q7/Q8 (2022), CSSE-016 Q21 (2021).', 2, 'wave1-mr02-sequence-rule',
 'mr02-sequence-rule', 'angel_original', 'practice_eligible', 1, true, 'Applying the rule forwards instead of reversing it (e.g. multiplying 31 by 2 instead of subtracting then dividing).'),

('mr02-seq-04-fwd', 'maths', 'QT-MR-05', array['csse'], 'easy', 'short-answer', 60,
 $json${"id":"mr02-seq-04-fwd","marks":1,"skill":"algebra","answer":"38","question":"A rule is: multiply by 5, then add 3. What is the output when the input is 7?","workingSteps":["7 × 5 = 35","35 + 3 = 38"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-05, competency MR-02. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q5/Q11/Q15 (2023), CSSE-011 Q7/Q8 (2022), CSSE-016 Q21 (2021).', 2, 'wave1-mr02-sequence-rule',
 'mr02-sequence-rule', 'angel_original', 'practice_eligible', 1, true, 'Forgetting to apply both steps (e.g. giving 35, the multiplication only, without adding 3).'),

('mr02-seq-04-inv', 'maths', 'QT-MR-05', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr02-seq-04-inv","marks":1,"skill":"algebra","answer":"10","question":"A rule is: multiply by 5, then add 3. The output is 53. What was the input?","workingSteps":["Reverse the rule: subtract 3 first, then divide by 5","53 - 3 = 50","50 ÷ 5 = 10"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-05, competency MR-02. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q5/Q11/Q15 (2023), CSSE-011 Q7/Q8 (2022), CSSE-016 Q21 (2021).', 2, 'wave1-mr02-sequence-rule',
 'mr02-sequence-rule', 'angel_original', 'practice_eligible', 1, true, 'Applying the rule forwards instead of reversing it (e.g. multiplying 53 by 5 instead of subtracting then dividing).'),

('mr02-seq-05-fwd', 'maths', 'QT-MR-05', array['csse'], 'easy', 'short-answer', 60,
 $json${"id":"mr02-seq-05-fwd","marks":1,"skill":"algebra","answer":"22","question":"A rule is: multiply by 6, then add 4. What is the output when the input is 3?","workingSteps":["3 × 6 = 18","18 + 4 = 22"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-05, competency MR-02. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q5/Q11/Q15 (2023), CSSE-011 Q7/Q8 (2022), CSSE-016 Q21 (2021).', 2, 'wave1-mr02-sequence-rule',
 'mr02-sequence-rule', 'angel_original', 'practice_eligible', 1, true, 'Forgetting to apply both steps (e.g. giving 18, the multiplication only, without adding 4).'),

('mr02-seq-05-inv', 'maths', 'QT-MR-05', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr02-seq-05-inv","marks":1,"skill":"algebra","answer":"6","question":"A rule is: multiply by 6, then add 4. The output is 40. What was the input?","workingSteps":["Reverse the rule: subtract 4 first, then divide by 6","40 - 4 = 36","36 ÷ 6 = 6"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-05, competency MR-02. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q5/Q11/Q15 (2023), CSSE-011 Q7/Q8 (2022), CSSE-016 Q21 (2021).', 2, 'wave1-mr02-sequence-rule',
 'mr02-sequence-rule', 'angel_original', 'practice_eligible', 1, true, 'Applying the rule forwards instead of reversing it (e.g. multiplying 40 by 6 instead of subtracting then dividing).'),

('mr02-sub-01', 'maths', 'QT-MR-06', array['csse'], 'hard', 'short-answer', 60,
 $json${"id":"mr02-sub-01","marks":1,"skill":"algebra","answer":"A=4, C=2","question":"B = 3A and 2C = A. If A + B + C = 18, find A and C.","workingSteps":["Express everything in terms of A: B = 3A, C = A ÷ 2","A + 3A + A ÷ 2 = 18","Solving gives A = 4, so B = 12 and C = 2"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-06, competency MR-02. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q8/Q18 (2023), CSSE-011 Q6/Q18 (2022), CSSE-016 Q6 (2021).', 2, 'wave1-mr02-substitution',
 'mr02-substitution', 'angel_original', 'practice_eligible', 1, true, 'Substituting only one relationship and treating the other unknown as still free, or solving for B instead of the two values actually asked for.'),

('mr02-sub-02', 'maths', 'QT-MR-06', array['csse'], 'hard', 'short-answer', 60,
 $json${"id":"mr02-sub-02","marks":1,"skill":"algebra","answer":"A=6, C=2","question":"B = 2A and 3C = A. If A + B + C = 20, find A and C.","workingSteps":["Express everything in terms of A: B = 2A, C = A ÷ 3","A + 2A + A ÷ 3 = 20","Solving gives A = 6, so B = 12 and C = 2"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-06, competency MR-02. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q8/Q18 (2023), CSSE-011 Q6/Q18 (2022), CSSE-016 Q6 (2021).', 2, 'wave1-mr02-substitution',
 'mr02-substitution', 'angel_original', 'practice_eligible', 1, true, 'Substituting only one relationship and treating the other unknown as still free, or solving for B instead of the two values actually asked for.'),

('mr02-sub-03', 'maths', 'QT-MR-06', array['csse'], 'hard', 'short-answer', 60,
 $json${"id":"mr02-sub-03","marks":1,"skill":"algebra","answer":"A=5, C=1","question":"B = 4A and 5C = A. If A + B + C = 26, find A and C.","workingSteps":["Express everything in terms of A: B = 4A, C = A ÷ 5","A + 4A + A ÷ 5 = 26","Solving gives A = 5, so B = 20 and C = 1"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-06, competency MR-02. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q8/Q18 (2023), CSSE-011 Q6/Q18 (2022), CSSE-016 Q6 (2021).', 2, 'wave1-mr02-substitution',
 'mr02-substitution', 'angel_original', 'practice_eligible', 1, true, 'Substituting only one relationship and treating the other unknown as still free, or solving for B instead of the two values actually asked for.'),

('mr02-sub-04', 'maths', 'QT-MR-06', array['csse'], 'hard', 'short-answer', 60,
 $json${"id":"mr02-sub-04","marks":1,"skill":"algebra","answer":"A=9, C=3","question":"B = A and 3C = A. If A + B + C = 21, find A and C.","workingSteps":["Express everything in terms of A: B = 1A, C = A ÷ 3","A + 1A + A ÷ 3 = 21","Solving gives A = 9, so B = 9 and C = 3"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-06, competency MR-02. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q8/Q18 (2023), CSSE-011 Q6/Q18 (2022), CSSE-016 Q6 (2021).', 2, 'wave1-mr02-substitution',
 'mr02-substitution', 'angel_original', 'practice_eligible', 1, true, 'Substituting only one relationship and treating the other unknown as still free, or solving for B instead of the two values actually asked for.'),

('mr02-sub-05', 'maths', 'QT-MR-06', array['csse'], 'hard', 'short-answer', 60,
 $json${"id":"mr02-sub-05","marks":1,"skill":"algebra","answer":"A=10, C=2","question":"B = 2A and 5C = A. If A + B + C = 32, find A and C.","workingSteps":["Express everything in terms of A: B = 2A, C = A ÷ 5","A + 2A + A ÷ 5 = 32","Solving gives A = 10, so B = 20 and C = 2"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-06, competency MR-02. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q8/Q18 (2023), CSSE-011 Q6/Q18 (2022), CSSE-016 Q6 (2021).', 2, 'wave1-mr02-substitution',
 'mr02-substitution', 'angel_original', 'practice_eligible', 1, true, 'Substituting only one relationship and treating the other unknown as still free, or solving for B instead of the two values actually asked for.'),

('mr03-ang-01', 'maths', 'QT-MR-07', array['csse'], 'easy', 'short-answer', 60,
 $json${"id":"mr03-ang-01","marks":1,"skill":"geometry","answer":"70°","question":"A triangle has angles of 48°, 62° and one unknown angle. What is the size of the unknown angle?","workingSteps":["The angles in a triangle always add up to 180°","48 + 62 = 110","180 - 110 = 70"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-07, competency MR-03. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q7/Q12 (2023), CSSE-011 Q12/Q17 (2022), CSSE-016 Q11 (2021).', 2, 'wave1-mr03-angle-sum',
 'mr03-angle-sum', 'angel_original', 'practice_eligible', 1, true, 'Using the wrong total for the shape (e.g. using 180° for a quadrilateral instead of 360°), or adding all the known angles incorrectly.'),

('mr03-ang-02', 'maths', 'QT-MR-07', array['csse'], 'easy', 'short-answer', 60,
 $json${"id":"mr03-ang-02","marks":1,"skill":"geometry","answer":"60°","question":"A triangle has angles of 35°, 85° and one unknown angle. What is the size of the unknown angle?","workingSteps":["The angles in a triangle always add up to 180°","35 + 85 = 120","180 - 120 = 60"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-07, competency MR-03. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q7/Q12 (2023), CSSE-011 Q12/Q17 (2022), CSSE-016 Q11 (2021).', 2, 'wave1-mr03-angle-sum',
 'mr03-angle-sum', 'angel_original', 'practice_eligible', 1, true, 'Using the wrong total for the shape (e.g. using 180° for a quadrilateral instead of 360°), or adding all the known angles incorrectly.'),

('mr03-ang-03', 'maths', 'QT-MR-07', array['csse'], 'easy', 'short-answer', 60,
 $json${"id":"mr03-ang-03","marks":1,"skill":"geometry","answer":"63°","question":"A triangle has angles of 90°, 27° and one unknown angle. What is the size of the unknown angle?","workingSteps":["The angles in a triangle always add up to 180°","90 + 27 = 117","180 - 117 = 63"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-07, competency MR-03. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q7/Q12 (2023), CSSE-011 Q12/Q17 (2022), CSSE-016 Q11 (2021).', 2, 'wave1-mr03-angle-sum',
 'mr03-angle-sum', 'angel_original', 'practice_eligible', 1, true, 'Using the wrong total for the shape (e.g. using 180° for a quadrilateral instead of 360°), or adding all the known angles incorrectly.'),

('mr03-ang-04', 'maths', 'QT-MR-07', array['csse'], 'easy', 'short-answer', 60,
 $json${"id":"mr03-ang-04","marks":1,"skill":"geometry","answer":"40°","question":"A triangle has angles of 40°, 100° and one unknown angle. What is the size of the unknown angle?","workingSteps":["The angles in a triangle always add up to 180°","40 + 100 = 140","180 - 140 = 40"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-07, competency MR-03. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q7/Q12 (2023), CSSE-011 Q12/Q17 (2022), CSSE-016 Q11 (2021).', 2, 'wave1-mr03-angle-sum',
 'mr03-angle-sum', 'angel_original', 'practice_eligible', 1, true, 'Using the wrong total for the shape (e.g. using 180° for a quadrilateral instead of 360°), or adding all the known angles incorrectly.'),

('mr03-ang-05', 'maths', 'QT-MR-07', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr03-ang-05","marks":1,"skill":"geometry","answer":"95°","question":"A quadrilateral has angles of 90°, 90°, 85° and one unknown angle. What is the size of the unknown angle?","workingSteps":["The angles in a quadrilateral always add up to 360°","90 + 90 + 85 = 265","360 - 265 = 95"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-07, competency MR-03. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q7/Q12 (2023), CSSE-011 Q12/Q17 (2022), CSSE-016 Q11 (2021).', 2, 'wave1-mr03-angle-sum',
 'mr03-angle-sum', 'angel_original', 'practice_eligible', 1, true, 'Using the wrong total for the shape (e.g. using 180° for a quadrilateral instead of 360°), or adding all the known angles incorrectly.'),

('mr03-ang-06', 'maths', 'QT-MR-07', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr03-ang-06","marks":1,"skill":"geometry","answer":"85°","question":"A quadrilateral has angles of 70°, 110°, 95° and one unknown angle. What is the size of the unknown angle?","workingSteps":["The angles in a quadrilateral always add up to 360°","70 + 110 + 95 = 275","360 - 275 = 85"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-07, competency MR-03. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q7/Q12 (2023), CSSE-011 Q12/Q17 (2022), CSSE-016 Q11 (2021).', 2, 'wave1-mr03-angle-sum',
 'mr03-angle-sum', 'angel_original', 'practice_eligible', 1, true, 'Using the wrong total for the shape (e.g. using 180° for a quadrilateral instead of 360°), or adding all the known angles incorrectly.'),

('mr03-ang-07', 'maths', 'QT-MR-07', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr03-ang-07","marks":1,"skill":"geometry","answer":"80°","question":"A quadrilateral has angles of 120°, 60°, 100° and one unknown angle. What is the size of the unknown angle?","workingSteps":["The angles in a quadrilateral always add up to 360°","120 + 60 + 100 = 280","360 - 280 = 80"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-07, competency MR-03. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q7/Q12 (2023), CSSE-011 Q12/Q17 (2022), CSSE-016 Q11 (2021).', 2, 'wave1-mr03-angle-sum',
 'mr03-angle-sum', 'angel_original', 'practice_eligible', 1, true, 'Using the wrong total for the shape (e.g. using 180° for a quadrilateral instead of 360°), or adding all the known angles incorrectly.'),

('mr05-tf-01', 'maths', 'QT-MR-11', array['csse'], 'easy', 'short-answer', 60,
 $json${"id":"mr05-tf-01","marks":1,"skill":"number-properties","answer":"True","question":"True or False: 17 is a prime number."}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-11, competency MR-05. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q10 (2023), CSSE-011 Q13 (2022), CSSE-016 (2021).', 2, 'wave1-mr05-number-property',
 'mr05-number-property', 'angel_original', 'practice_eligible', 1, true, 'Confusing a related but different property (e.g. treating "not even" as the same as "prime", or miscalculating the stated value before judging it).'),

('mr05-tf-02', 'maths', 'QT-MR-11', array['csse'], 'easy', 'short-answer', 60,
 $json${"id":"mr05-tf-02","marks":1,"skill":"number-properties","answer":"False","question":"True or False: 51 is a prime number."}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-11, competency MR-05. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q10 (2023), CSSE-011 Q13 (2022), CSSE-016 (2021).', 2, 'wave1-mr05-number-property',
 'mr05-number-property', 'angel_original', 'practice_eligible', 1, true, 'Confusing a related but different property (e.g. treating "not even" as the same as "prime", or miscalculating the stated value before judging it).'),

('mr05-tf-03', 'maths', 'QT-MR-11', array['csse'], 'easy', 'short-answer', 60,
 $json${"id":"mr05-tf-03","marks":1,"skill":"number-properties","answer":"True","question":"True or False: 81 is a square number."}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-11, competency MR-05. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q10 (2023), CSSE-011 Q13 (2022), CSSE-016 (2021).', 2, 'wave1-mr05-number-property',
 'mr05-number-property', 'angel_original', 'practice_eligible', 1, true, 'Confusing a related but different property (e.g. treating "not even" as the same as "prime", or miscalculating the stated value before judging it).'),

('mr05-tf-04', 'maths', 'QT-MR-11', array['csse'], 'easy', 'short-answer', 60,
 $json${"id":"mr05-tf-04","marks":1,"skill":"number-properties","answer":"True","question":"True or False: The average of 3 and 11 is a prime number."}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-11, competency MR-05. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q10 (2023), CSSE-011 Q13 (2022), CSSE-016 (2021).', 2, 'wave1-mr05-number-property',
 'mr05-number-property', 'angel_original', 'practice_eligible', 1, true, 'Confusing a related but different property (e.g. treating "not even" as the same as "prime", or miscalculating the stated value before judging it).'),

('mr05-tf-05', 'maths', 'QT-MR-11', array['csse'], 'easy', 'short-answer', 60,
 $json${"id":"mr05-tf-05","marks":1,"skill":"number-properties","answer":"False","question":"True or False: The average of 6 and 10 is a prime number."}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-11, competency MR-05. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q10 (2023), CSSE-011 Q13 (2022), CSSE-016 (2021).', 2, 'wave1-mr05-number-property',
 'mr05-number-property', 'angel_original', 'practice_eligible', 1, true, 'Confusing a related but different property (e.g. treating "not even" as the same as "prime", or miscalculating the stated value before judging it).'),

('mr05-search-01', 'maths', 'QT-MR-11', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr05-search-01","marks":1,"skill":"number-properties","answer":"41","question":"What is the smallest prime number greater than 40?","workingSteps":["41 is not divisible by 2, 3, or 5","41 is prime, and no whole number between 40 and 41 exists"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-11, competency MR-05. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q10 (2023) only, LOW confidence sub-format, disclosed.', 2, 'wave1-mr05-number-property-search',
 'mr05-number-property-search', 'angel_original', 'practice_eligible', 1, true, null),

('mr05-search-02', 'maths', 'QT-MR-11', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr05-search-02","marks":1,"skill":"number-properties","answer":"29","question":"What is the largest prime number less than 30?","workingSteps":["29 is not divisible by 2, 3, or 5","29 is prime, and nothing between 29 and 30 needs checking"]}$json$,
 'Educational Increment 004, Wave 1. Assessment Brain QT-MR-11, competency MR-05. Deterministically generated by scripts/generate-mathematics-wave1.mjs (answer computed in code from the item''s own parameters, not hand-typed) and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q10 (2023) only, LOW confidence sub-format, disclosed.', 2, 'wave1-mr05-number-property-search',
 'mr05-number-property-search', 'angel_original', 'practice_eligible', 1, true, null)

on conflict (id) do nothing;

commit;
