-- Angel Digital 11+ — Migration 036
-- Educational Increment 005B: Mathematics Scale Wave 2, actual content.
--
-- 12 new Mathematics items across 4 NEW families (not values-variation of
-- Wave 1's families), all deterministically generated by
-- scripts/generate-mathematics-wave2.mjs and validated for duplicate
-- id/question/answer before authoring (PASS). Real-data structural-
-- signature check (scripts/report-structural-signatures.mjs) against all
-- 41 items across both waves found 10 distinct signatures and zero
-- cross-family collisions.
--
-- Families (each has an evidence-backed reason to exist, per the
-- directive's own instruction not to mechanically apply every structure
-- everywhere):
--
--   mr02-compare (QT-MR-06, MR-02, structure COMPARISON, ROUTINE, 3 items)
--     Evaluate two linear expressions at a given n and judge
--     Greater/Less/Equal. Genuinely distinct reasoning from Wave 1's
--     mr02-sequence-rule (apply-a-stated-rule) and mr02-substitution
--     (solve-a-system-for-an-unknown) — this is evaluate-then-compare,
--     with no unknown to solve for.
--
--   mr03-classify (QT-MR-07, MR-03, structure CLASSIFICATION, ROUTINE, 3
--     items) Given a triangle's three angles, classify it as
--     equilateral/isosceles/scalene via the equal-angles-imply-equal-
--     sides property. Genuinely distinct from Wave 1's mr03-angle-sum
--     (compute-the-missing-numeric-angle) — this asks what KIND of
--     shape, not a value.
--
--   mr04-far-percent (QT-MR-04, primary MR-04, supporting MR-01,
--     structure CONTEXTUAL PROBLEM SOLVING, FAR_TRANSFER, 3 items)
--     Two paired before/after prices establish a proportional
--     relationship with the words "percentage," "fraction," and "ratio"
--     never appearing anywhere in the prompt; the learner must recognise
--     the same proportional relationship applies to a second price and
--     derive it themselves, rather than being told which operation to
--     apply. This is the increment's genuine FAR_TRANSFER content —
--     Wave 1 and the Mathematics Reference Vertical's own Lesson 2
--     always explicitly named the operation ("Find X% of Y"); this
--     family deliberately does not.
--
--   mr04-mixed-divisibility (QT-MR-13, primary MR-04, supporting MR-05,
--     structure CONSTRAINT SATISFACTION, MIXED_TRANSFER, 3 items) A
--     population fits two simultaneous grouping conditions (a range
--     constraint plus two modular conditions). Genuinely requires MR-04's
--     multi-step interpretation to set up both conditions from the prose
--     AND MR-05's number-property/divisibility reasoning to search the
--     valid range for the unique number satisfying both — not incidental
--     arithmetic riding along with a primarily-MR-04 item. Every
--     parameter set was verified in code to have exactly one solution in
--     its stated range before being authored (a script assertion, not a
--     claim).
--
-- eligibility_status = 'provisional' throughout, per the Founder's Part
-- 17 instruction this round: new content begins Provisional unless the
-- canonical workflow (the ali_family_review mechanism, migration 034)
-- permits promotion. No self-promotion to practice_eligible or higher —
-- unlike Wave 1's items, these 12 will NOT appear in normal Practice
-- until a family review record exists and a separate, human-authorised
-- step promotes them. This is a deliberate tightening from Wave 1's own
-- precedent, not an oversight.
--
-- provenance = 'angel_original' throughout — no CSSE numeric combination,
-- story context, or wording reused; each family's authoring note cites
-- its real evidence basis (Question Type + Asset IDs) without
-- reproducing any of it.
--
-- Every question, workingSteps and misconception field checked for em/en
-- dash sentence punctuation by hand (found and fixed 2 occurrences before
-- writing this migration) — the Copy Quality Guard cannot scan database
-- content.
--
-- ali_question_bank has no browser-writable RLS/grant path — apply via
-- Supabase Dashboard > SQL Editor, same as every other migration.

begin;

insert into public.ali_question_bank
  (id, subject, skill, pathway, content_difficulty, question_type, estimated_time_seconds,
   prompt, explanation, mastery_threshold, learning_unit_id,
   family_id, provenance, eligibility_status, content_version, active, addresses_misconception,
   transfer_class, supporting_competencies)
values

('mr02-cmp-01', 'maths', 'QT-MR-06', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr02-cmp-01","marks":1,"skill":"algebra","answer":"Equal","question":"When n = 4, is 3n + 5 greater than, less than, or equal to 5n − 3? Answer Greater, Less, or Equal.","workingSteps":["3n + 5 at n=4: 3×4 + 5 = 17","5n − 3 at n=4: 5×4 − 3 = 17","17 = 17, so the answer is Equal"]}$json$,
 'Educational Increment 005B, Wave 2. Assessment Brain QT-MR-06, primary competency MR-02. Structure: COMPARISON. Transfer class: ROUTINE. Deterministically generated by scripts/generate-mathematics-wave2.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q8/Q18 (2023), CSSE-011 Q6/Q18 (2022), CSSE-016 Q6 (2021).', 2, 'wave2-mr02-compare',
 'mr02-compare', 'angel_original', 'provisional', 1, true, 'Evaluating only one expression, or evaluating both but comparing them the wrong way round.',
 'ROUTINE', null),

('mr02-cmp-02', 'maths', 'QT-MR-06', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr02-cmp-02","marks":1,"skill":"algebra","answer":"Greater","question":"When n = 3, is 2n + 9 greater than, less than, or equal to 4n + 1? Answer Greater, Less, or Equal.","workingSteps":["2n + 9 at n=3: 2×3 + 9 = 15","4n + 1 at n=3: 4×3 + 1 = 13","15 > 13, so the answer is Greater"]}$json$,
 'Educational Increment 005B, Wave 2. Assessment Brain QT-MR-06, primary competency MR-02. Structure: COMPARISON. Transfer class: ROUTINE. Deterministically generated by scripts/generate-mathematics-wave2.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q8/Q18 (2023), CSSE-011 Q6/Q18 (2022), CSSE-016 Q6 (2021).', 2, 'wave2-mr02-compare',
 'mr02-compare', 'angel_original', 'provisional', 1, true, 'Evaluating only one expression, or evaluating both but comparing them the wrong way round.',
 'ROUTINE', null),

('mr02-cmp-03', 'maths', 'QT-MR-06', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr02-cmp-03","marks":1,"skill":"algebra","answer":"Less","question":"When n = 5, is 2n + 1 greater than, less than, or equal to 4n − 5? Answer Greater, Less, or Equal.","workingSteps":["2n + 1 at n=5: 2×5 + 1 = 11","4n − 5 at n=5: 4×5 − 5 = 15","11 < 15, so the answer is Less"]}$json$,
 'Educational Increment 005B, Wave 2. Assessment Brain QT-MR-06, primary competency MR-02. Structure: COMPARISON. Transfer class: ROUTINE. Deterministically generated by scripts/generate-mathematics-wave2.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q8/Q18 (2023), CSSE-011 Q6/Q18 (2022), CSSE-016 Q6 (2021).', 2, 'wave2-mr02-compare',
 'mr02-compare', 'angel_original', 'provisional', 1, true, 'Evaluating only one expression, or evaluating both but comparing them the wrong way round.',
 'ROUTINE', null),

('mr03-cls-01', 'maths', 'QT-MR-07', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr03-cls-01","marks":1,"skill":"geometry","answer":"Equilateral","question":"A triangle has angles of 60°, 60°, 60°. Is it isosceles, equilateral or scalene?","workingSteps":["Equal angles mean equal opposite sides","All three angles are equal, so all three sides are equal: equilateral"]}$json$,
 'Educational Increment 005B, Wave 2. Assessment Brain QT-MR-07, primary competency MR-03. Structure: CLASSIFICATION. Transfer class: ROUTINE. Deterministically generated by scripts/generate-mathematics-wave2.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q7/Q12 (2023), CSSE-011 Q12/Q17 (2022), CSSE-016 Q11 (2021).', 2, 'wave2-mr03-classify',
 'mr03-classify', 'angel_original', 'provisional', 1, true, 'Assuming a triangle with one right or notably large angle must be scalene without checking whether two angles are actually equal.',
 'ROUTINE', null),

('mr03-cls-02', 'maths', 'QT-MR-07', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr03-cls-02","marks":1,"skill":"geometry","answer":"Isosceles","question":"A triangle has angles of 90°, 45°, 45°. Is it isosceles, equilateral or scalene?","workingSteps":["Equal angles mean equal opposite sides","Exactly two angles are equal, so exactly two sides are equal: isosceles"]}$json$,
 'Educational Increment 005B, Wave 2. Assessment Brain QT-MR-07, primary competency MR-03. Structure: CLASSIFICATION. Transfer class: ROUTINE. Deterministically generated by scripts/generate-mathematics-wave2.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q7/Q12 (2023), CSSE-011 Q12/Q17 (2022), CSSE-016 Q11 (2021).', 2, 'wave2-mr03-classify',
 'mr03-classify', 'angel_original', 'provisional', 1, true, 'Assuming a triangle with one right or notably large angle must be scalene without checking whether two angles are actually equal.',
 'ROUTINE', null),

('mr03-cls-03', 'maths', 'QT-MR-07', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr03-cls-03","marks":1,"skill":"geometry","answer":"Scalene","question":"A triangle has angles of 80°, 60°, 40°. Is it isosceles, equilateral or scalene?","workingSteps":["Equal angles mean equal opposite sides","All three angles are different, so all three sides are different: scalene"]}$json$,
 'Educational Increment 005B, Wave 2. Assessment Brain QT-MR-07, primary competency MR-03. Structure: CLASSIFICATION. Transfer class: ROUTINE. Deterministically generated by scripts/generate-mathematics-wave2.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q7/Q12 (2023), CSSE-011 Q12/Q17 (2022), CSSE-016 Q11 (2021).', 2, 'wave2-mr03-classify',
 'mr03-classify', 'angel_original', 'provisional', 1, true, 'Assuming a triangle with one right or notably large angle must be scalene without checking whether two angles are actually equal.',
 'ROUTINE', null),

('mr04-far-01', 'maths', 'QT-MR-04', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr04-far-01","marks":1,"skill":"percentage","answer":"£45","question":"A shop reduces every price by the same amount, proportionally. A book that cost £20 now costs £15. Using the same reduction, what is the new price of a jacket that originally cost £60?","workingSteps":["The book's new price is £15 out of an original £20. Every price keeps the same fraction of its original value","£15 out of £20 is the same fraction as £45 out of £60","£60 × (15/20) = £45"]}$json$,
 'Educational Increment 005B, Wave 2. Assessment Brain QT-MR-04, primary competency MR-04, supporting MR-01. Structure: CONTEXTUAL PROBLEM SOLVING. Transfer class: FAR_TRANSFER. Deterministically generated by scripts/generate-mathematics-wave2.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q1/Q13 (2023), CSSE-011 Q1/Q2/Q3 (2022), CSSE-016 Q1/Q2 (2021).', 2, 'wave2-mr04-far-percent',
 'mr04-far-percent', 'angel_original', 'provisional', 1, true, 'Subtracting the same fixed amount (£5) from the second price instead of applying the same proportional reduction. The reduction is a fraction of the price, not a fixed amount.',
 'FAR_TRANSFER', array['MR-01']),

('mr04-far-02', 'maths', 'QT-MR-04', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr04-far-02","marks":1,"skill":"percentage","answer":"£60","question":"A shop reduces every price by the same amount, proportionally. A book that cost £50 now costs £40. Using the same reduction, what is the new price of a jacket that originally cost £75?","workingSteps":["The book's new price is £40 out of an original £50. Every price keeps the same fraction of its original value","£40 out of £50 is the same fraction as £60 out of £75","£75 × (40/50) = £60"]}$json$,
 'Educational Increment 005B, Wave 2. Assessment Brain QT-MR-04, primary competency MR-04, supporting MR-01. Structure: CONTEXTUAL PROBLEM SOLVING. Transfer class: FAR_TRANSFER. Deterministically generated by scripts/generate-mathematics-wave2.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q1/Q13 (2023), CSSE-011 Q1/Q2/Q3 (2022), CSSE-016 Q1/Q2 (2021).', 2, 'wave2-mr04-far-percent',
 'mr04-far-percent', 'angel_original', 'provisional', 1, true, 'Subtracting the same fixed amount (£10) from the second price instead of applying the same proportional reduction. The reduction is a fraction of the price, not a fixed amount.',
 'FAR_TRANSFER', array['MR-01']),

('mr04-far-03', 'maths', 'QT-MR-04', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr04-far-03","marks":1,"skill":"percentage","answer":"£40","question":"A shop reduces every price by the same amount, proportionally. A book that cost £16 now costs £10. Using the same reduction, what is the new price of a jacket that originally cost £64?","workingSteps":["The book's new price is £10 out of an original £16. Every price keeps the same fraction of its original value","£10 out of £16 is the same fraction as £40 out of £64","£64 × (10/16) = £40"]}$json$,
 'Educational Increment 005B, Wave 2. Assessment Brain QT-MR-04, primary competency MR-04, supporting MR-01. Structure: CONTEXTUAL PROBLEM SOLVING. Transfer class: FAR_TRANSFER. Deterministically generated by scripts/generate-mathematics-wave2.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q1/Q13 (2023), CSSE-011 Q1/Q2/Q3 (2022), CSSE-016 Q1/Q2 (2021).', 2, 'wave2-mr04-far-percent',
 'mr04-far-percent', 'angel_original', 'provisional', 1, true, 'Subtracting the same fixed amount (£6) from the second price instead of applying the same proportional reduction. The reduction is a fraction of the price, not a fixed amount.',
 'FAR_TRANSFER', array['MR-01']),

('mr04-mix-01', 'maths', 'QT-MR-13', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr04-mix-01","marks":1,"skill":"number-properties","answer":"95","question":"A school has more than 90 but fewer than 100 students. If they are put into groups of 6, there are 5 left over. If they are split into groups of 5, there are none left over. How many are there?","workingSteps":["Multiples of 5 between 90 and 100: check each against the other condition","Only 95 also leaves 5 over when divided by 6"]}$json$,
 'Educational Increment 005B, Wave 2. Assessment Brain QT-MR-13, primary competency MR-04, supporting MR-05. Structure: CONSTRAINT SATISFACTION. Transfer class: MIXED_TRANSFER. Deterministically generated by scripts/generate-mathematics-wave2.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006, CSSE-016 (QT-MR-13, Best-Value/Combinatorial Word Problem).', 2, 'wave2-mr04-mixed-divisibility',
 'mr04-mixed-divisibility', 'angel_original', 'provisional', 1, true, 'Finding a number that satisfies only one of the two conditions and stopping there, instead of checking both conditions together.',
 'MIXED_TRANSFER', array['MR-05']),

('mr04-mix-02', 'maths', 'QT-MR-13', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr04-mix-02","marks":1,"skill":"number-properties","answer":"133","question":"A youth club has more than 130 but fewer than 150 members. If they are put into groups of 4, there is 1 left over. If they are split into groups of 7, there are none left over. How many are there?","workingSteps":["Multiples of 7 between 130 and 150: check each against the other condition","Only 133 also leaves 1 over when divided by 4"]}$json$,
 'Educational Increment 005B, Wave 2. Assessment Brain QT-MR-13, primary competency MR-04, supporting MR-05. Structure: CONSTRAINT SATISFACTION. Transfer class: MIXED_TRANSFER. Deterministically generated by scripts/generate-mathematics-wave2.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006, CSSE-016 (QT-MR-13, Best-Value/Combinatorial Word Problem).', 2, 'wave2-mr04-mixed-divisibility',
 'mr04-mixed-divisibility', 'angel_original', 'provisional', 1, true, 'Finding a number that satisfies only one of the two conditions and stopping there, instead of checking both conditions together.',
 'MIXED_TRANSFER', array['MR-05']),

('mr04-mix-03', 'maths', 'QT-MR-13', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr04-mix-03","marks":1,"skill":"number-properties","answer":"152","question":"A choir has more than 145 but fewer than 160 singers. If they are put into groups of 6, there are 2 left over. If they are split into groups of 8, there are none left over. How many are there?","workingSteps":["Multiples of 8 between 145 and 160: check each against the other condition","Only 152 also leaves 2 over when divided by 6"]}$json$,
 'Educational Increment 005B, Wave 2. Assessment Brain QT-MR-13, primary competency MR-04, supporting MR-05. Structure: CONSTRAINT SATISFACTION. Transfer class: MIXED_TRANSFER. Deterministically generated by scripts/generate-mathematics-wave2.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006, CSSE-016 (QT-MR-13, Best-Value/Combinatorial Word Problem).', 2, 'wave2-mr04-mixed-divisibility',
 'mr04-mixed-divisibility', 'angel_original', 'provisional', 1, true, 'Finding a number that satisfies only one of the two conditions and stopping there, instead of checking both conditions together.',
 'MIXED_TRANSFER', array['MR-05'])

on conflict (id) do nothing;

commit;
