-- Angel Digital 11+ — Migration 039
-- Educational Increment 006: Mathematics Scale Wave 3.
--
-- 19 new Mathematics items across 6 NEW families, deterministically
-- generated (scripts/generate-mathematics-wave3.mjs), validated for
-- duplicate id/question/answer, cross-checked against this migration
-- file byte-for-byte (scripts/verify-wave3-migration.mjs). Two real
-- phrasing defects were found during authoring and fixed before this
-- file was written (a doubled "= ?" in the missing-operand template; an
-- awkward passive-voice construction in one far-transfer item) — caught
-- by reading the generator's own output, not assumed correct because the
-- validator passed.
--
-- Families, broadening beyond Wave 1/2's MR-02/MR-03/MR-04/MR-05 single
-- structures each:
--
--   mr01-missing-operand (QT-MR-02, MR-01, REVERSE REASONING, ROUTINE,
--     4 items) Solve for an unknown operand in an otherwise-complete
--     arithmetic statement. QT-MR-02's own evidenced Measurement Purpose:
--     "tests inverse-operation reasoning rather than forward calculation
--     alone." First MR-01 content added since the Content Inventory
--     flagged MR-01 as already dominant — deliberately a genuinely new
--     structure (reverse reasoning), not more direct-computation volume.
--
--   mr03-coordinate (QT-MR-08, MR-03, UNUSUAL REPRESENTATION, ROUTINE, 3
--     items) Coordinate reflection/translation — a representation (a
--     coordinate grid) not used anywhere else in the bank.
--
--   mr05-constrained-multiple (QT-MR-11, MR-05, CONSTRAINT SATISFACTION,
--     ROUTINE, 3 items) Smallest/largest common multiple satisfying a
--     bound — genuine LCM reasoning, distinct from Wave 1's true/false
--     judgement and Wave 2's prime search sub-formats of the same QT.
--
--   mr02-far-ratio-context (QT-MR-06, primary MR-02 + supporting MR-01,
--     CONTEXTUAL PROBLEM SOLVING, FAR_TRANSFER, 3 items) A part-whole
--     ratio relationship embedded in prose with no algebra notation and
--     no instruction to "solve" — a second, deliberately DIFFERENT
--     far-transfer representation from Wave 2's before/after price ratio.
--
--   mr03-mixed-perimeter (QT-MR-07, primary MR-03 + supporting MR-01,
--     MULTI-STEP APPLICATION, MIXED_TRANSFER, 3 items) Area and one side
--     given; perimeter asked. Genuinely requires MR-03's area/perimeter
--     relationship AND MR-01 arithmetic — not incidental.
--
--   mr04-far-recipe (QT-MR-04, primary MR-04 + supporting MR-01,
--     CONTEXTUAL PROBLEM SOLVING, FAR_TRANSFER, 3 items) Unitary-method
--     recipe scaling — a second, genuinely different far-transfer
--     context from Wave 2's price-ratio family, addressing that wave's
--     own disclosed single-context limitation
--     (MATHEMATICS_WAVE2_REVIEW_PACKS.md).
--
-- eligibility_status = 'provisional' throughout — same discipline as
-- Wave 2 (005B), per the standing Founder instruction that new content
-- does not become Practice Eligible merely because the generator passed.
-- provenance = 'angel_original' throughout.
--
-- Every question, workingSteps and misconception field checked for em/en
-- dash sentence punctuation programmatically (scripts/generate-
-- mathematics-wave3.mjs's own validator includes this check) before this
-- migration was written.
--
-- ali_question_bank has no browser-writable RLS/grant path — apply via
-- Supabase Dashboard > SQL Editor, same as every other migration.

begin;

insert into public.ali_question_bank
  (id, subject, skill, pathway, content_difficulty, question_type, estimated_time_seconds,
   prompt, explanation, mastery_threshold, learning_unit_id,
   family_id, provenance, eligibility_status, content_version, active, addresses_misconception,
   transfer_class, supporting_competencies)
values

('mr01-mop-01', 'maths', 'QT-MR-02', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr01-mop-01","marks":1,"skill":"arithmetic","answer":"12","question":"▢ × 7 = 84. What number replaces the box?","workingSteps":["Rearrange to find the missing number: 12"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-02, primary competency MR-01. Structure: REVERSE REASONING. Transfer class: ROUTINE. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q2(b)(c)(d) (2023), CSSE-016 Q2(c)(d)/Q3(a)(b) (2021).', 2, 'wave3-mr01-missing-operand',
 'mr01-missing-operand', 'angel_original', 'provisional', 1, true, 'Applying the stated operation directly to the two visible numbers instead of using its inverse to find the missing one.',
 'ROUTINE', null),

('mr01-mop-02', 'maths', 'QT-MR-02', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr01-mop-02","marks":1,"skill":"arithmetic","answer":"7","question":"56 ÷ ▢ = 8. What number replaces the box?","workingSteps":["Rearrange to find the missing number: 7"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-02, primary competency MR-01. Structure: REVERSE REASONING. Transfer class: ROUTINE. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q2(b)(c)(d) (2023), CSSE-016 Q2(c)(d)/Q3(a)(b) (2021).', 2, 'wave3-mr01-missing-operand',
 'mr01-missing-operand', 'angel_original', 'provisional', 1, true, 'Applying the stated operation directly to the two visible numbers instead of using its inverse to find the missing one.',
 'ROUTINE', null),

('mr01-mop-03', 'maths', 'QT-MR-02', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr01-mop-03","marks":1,"skill":"arithmetic","answer":"38","question":"▢ − 15 = 23. What number replaces the box?","workingSteps":["Rearrange to find the missing number: 38"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-02, primary competency MR-01. Structure: REVERSE REASONING. Transfer class: ROUTINE. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q2(b)(c)(d) (2023), CSSE-016 Q2(c)(d)/Q3(a)(b) (2021).', 2, 'wave3-mr01-missing-operand',
 'mr01-missing-operand', 'angel_original', 'provisional', 1, true, 'Applying the stated operation directly to the two visible numbers instead of using its inverse to find the missing one.',
 'ROUTINE', null),

('mr01-mop-04', 'maths', 'QT-MR-02', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr01-mop-04","marks":1,"skill":"arithmetic","answer":"23","question":"▢ + 27 = 50. What number replaces the box?","workingSteps":["Rearrange to find the missing number: 23"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-02, primary competency MR-01. Structure: REVERSE REASONING. Transfer class: ROUTINE. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q2(b)(c)(d) (2023), CSSE-016 Q2(c)(d)/Q3(a)(b) (2021).', 2, 'wave3-mr01-missing-operand',
 'mr01-missing-operand', 'angel_original', 'provisional', 1, true, 'Applying the stated operation directly to the two visible numbers instead of using its inverse to find the missing one.',
 'ROUTINE', null),

('mr03-coord-01', 'maths', 'QT-MR-08', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr03-coord-01","marks":1,"skill":"geometry","answer":"(3, -5)","question":"Point A is at (3, 5). It is reflected in the x-axis. What are the new coordinates?","workingSteps":["Reflecting in the x-axis keeps x the same and reverses the sign of y","(3, 5) becomes (3, -5)"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-08, primary competency MR-03. Structure: UNUSUAL REPRESENTATION. Transfer class: ROUTINE. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: AEP-004 QT-MR-08 (Coordinate/Transformation Reasoning), CSSE Multi-Year Pattern Analysis.', 2, 'wave3-mr03-coordinate',
 'mr03-coordinate', 'angel_original', 'provisional', 1, true, 'Reflecting in the wrong axis (negating the wrong coordinate), or applying a translation in the wrong direction.',
 'ROUTINE', null),

('mr03-coord-02', 'maths', 'QT-MR-08', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr03-coord-02","marks":1,"skill":"geometry","answer":"(-4, -2)","question":"Point B is at (4, -2). It is reflected in the y-axis. What are the new coordinates?","workingSteps":["Reflecting in the y-axis keeps y the same and reverses the sign of x","(4, -2) becomes (-4, -2)"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-08, primary competency MR-03. Structure: UNUSUAL REPRESENTATION. Transfer class: ROUTINE. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: AEP-004 QT-MR-08 (Coordinate/Transformation Reasoning), CSSE Multi-Year Pattern Analysis.', 2, 'wave3-mr03-coordinate',
 'mr03-coordinate', 'angel_original', 'provisional', 1, true, 'Reflecting in the wrong axis (negating the wrong coordinate), or applying a translation in the wrong direction.',
 'ROUTINE', null),

('mr03-coord-03', 'maths', 'QT-MR-08', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr03-coord-03","marks":1,"skill":"geometry","answer":"(2, 4)","question":"Point C is at (-3, 6). It is translated 5 units right and 2 units down. What are the new coordinates?","workingSteps":["Right increases x, down decreases y","(-3 + 5, 6 - 2) = (2, 4)"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-08, primary competency MR-03. Structure: UNUSUAL REPRESENTATION. Transfer class: ROUTINE. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: AEP-004 QT-MR-08 (Coordinate/Transformation Reasoning), CSSE Multi-Year Pattern Analysis.', 2, 'wave3-mr03-coordinate',
 'mr03-coordinate', 'angel_original', 'provisional', 1, true, 'Reflecting in the wrong axis (negating the wrong coordinate), or applying a translation in the wrong direction.',
 'ROUTINE', null),

('mr05-mult-01', 'maths', 'QT-MR-11', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr05-mult-01","marks":1,"skill":"number-properties","answer":"36","question":"What is the smallest multiple of both 4 and 9 that is greater than 30?","workingSteps":["The lowest common multiple of 4 and 9 is 36","The smallest multiple of 36 above 30 is 36"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-11, primary competency MR-05. Structure: CONSTRAINT SATISFACTION. Transfer class: ROUTINE. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q10 (2023), CSSE-011 Q13 (2022), CSSE-016 (2021).', 2, 'wave3-mr05-constrained-multiple',
 'mr05-constrained-multiple', 'angel_original', 'provisional', 1, true, 'Finding a multiple of only one of the two numbers, or finding the lowest common multiple itself without then checking it against the stated bound.',
 'ROUTINE', null),

('mr05-mult-02', 'maths', 'QT-MR-11', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr05-mult-02","marks":1,"skill":"number-properties","answer":"48","question":"What is the smallest multiple of both 6 and 8 that is greater than 40?","workingSteps":["The lowest common multiple of 6 and 8 is 24","The smallest multiple of 24 above 40 is 48"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-11, primary competency MR-05. Structure: CONSTRAINT SATISFACTION. Transfer class: ROUTINE. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q10 (2023), CSSE-011 Q13 (2022), CSSE-016 (2021).', 2, 'wave3-mr05-constrained-multiple',
 'mr05-constrained-multiple', 'angel_original', 'provisional', 1, true, 'Finding a multiple of only one of the two numbers, or finding the lowest common multiple itself without then checking it against the stated bound.',
 'ROUTINE', null),

('mr05-mult-03', 'maths', 'QT-MR-11', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr05-mult-03","marks":1,"skill":"number-properties","answer":"45","question":"What is the largest multiple of both 3 and 5 that is less than 50?","workingSteps":["The lowest common multiple of 3 and 5 is 15","The largest multiple of 15 below 50 is 45"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-11, primary competency MR-05. Structure: CONSTRAINT SATISFACTION. Transfer class: ROUTINE. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q10 (2023), CSSE-011 Q13 (2022), CSSE-016 (2021).', 2, 'wave3-mr05-constrained-multiple',
 'mr05-constrained-multiple', 'angel_original', 'provisional', 1, true, 'Finding a multiple of only one of the two numbers, or finding the lowest common multiple itself without then checking it against the stated bound.',
 'ROUTINE', null),

('mr02-far-01', 'maths', 'QT-MR-06', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr02-far-01","marks":1,"skill":"algebra","answer":"8","question":"Sam has twice as much money as Tom. Between them they have £36. If Tom then spends £4, how much does Tom have left?","workingSteps":["Tom's share plus 2 times Tom's share equals 36","Tom's share is 36 ÷ 3 = 12","12 - 4 = 8"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-06, primary competency MR-02, supporting MR-01. Structure: CONTEXTUAL PROBLEM SOLVING. Transfer class: FAR_TRANSFER. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q8/Q18 (2023), CSSE-011 Q6/Q18 (2022), CSSE-016 Q6 (2021).', 2, 'wave3-mr02-far-ratio-context',
 'mr02-far-ratio-context', 'angel_original', 'provisional', 1, true, 'Splitting the total evenly instead of using the stated 2:1 relationship.',
 'FAR_TRANSFER', array['MR-01']),

('mr02-far-02', 'maths', 'QT-MR-06', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr02-far-02","marks":1,"skill":"algebra","answer":"7","question":"Amy has three times as many stickers as Ben. Between them they have 48 stickers. If Ben then gives away 5 stickers, how many does Ben have left?","workingSteps":["Ben's share plus 3 times Ben's share equals 48","Ben's share is 48 ÷ 4 = 12","12 - 5 = 7"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-06, primary competency MR-02, supporting MR-01. Structure: CONTEXTUAL PROBLEM SOLVING. Transfer class: FAR_TRANSFER. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q8/Q18 (2023), CSSE-011 Q6/Q18 (2022), CSSE-016 Q6 (2021).', 2, 'wave3-mr02-far-ratio-context',
 'mr02-far-ratio-context', 'angel_original', 'provisional', 1, true, 'Splitting the total evenly instead of using the stated 3:1 relationship.',
 'FAR_TRANSFER', array['MR-01']),

('mr02-far-03', 'maths', 'QT-MR-06', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr02-far-03","marks":1,"skill":"algebra","answer":"9","question":"A rope is cut into two pieces. The longer piece is four times the length of the shorter piece. Together they measure 60cm. If 3cm is then cut from the shorter piece, how long is it now?","workingSteps":["the shorter piece's share plus 4 times the shorter piece's share equals 60","the shorter piece's share is 60 ÷ 5 = 12","12 - 3 = 9"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-06, primary competency MR-02, supporting MR-01. Structure: CONTEXTUAL PROBLEM SOLVING. Transfer class: FAR_TRANSFER. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q8/Q18 (2023), CSSE-011 Q6/Q18 (2022), CSSE-016 Q6 (2021).', 2, 'wave3-mr02-far-ratio-context',
 'mr02-far-ratio-context', 'angel_original', 'provisional', 1, true, 'Splitting the total evenly instead of using the stated 4:1 relationship.',
 'FAR_TRANSFER', array['MR-01']),

('mr03-mix-01', 'maths', 'QT-MR-07', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr03-mix-01","marks":1,"skill":"geometry","answer":"28m","question":"A rectangular garden has an area of 48 m² and one side is 6m. What is the perimeter?","workingSteps":["The other side is 48 ÷ 6 = 8m","Perimeter = 2 × (6 + 8) = 28m"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-07, primary competency MR-03, supporting MR-01. Structure: MULTI-STEP APPLICATION. Transfer class: MIXED_TRANSFER. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q7/Q12 (2023), CSSE-011 Q12/Q17 (2022), CSSE-016 Q11 (2021).', 2, 'wave3-mr03-mixed-perimeter',
 'mr03-mixed-perimeter', 'angel_original', 'provisional', 1, true, 'Using the area value directly as part of the perimeter calculation, or forgetting to double the sum of both sides.',
 'MIXED_TRANSFER', array['MR-01']),

('mr03-mix-02', 'maths', 'QT-MR-07', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr03-mix-02","marks":1,"skill":"geometry","answer":"34m","question":"A rectangular field has an area of 72 m² and one side is 9m. What is the perimeter?","workingSteps":["The other side is 72 ÷ 9 = 8m","Perimeter = 2 × (9 + 8) = 34m"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-07, primary competency MR-03, supporting MR-01. Structure: MULTI-STEP APPLICATION. Transfer class: MIXED_TRANSFER. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q7/Q12 (2023), CSSE-011 Q12/Q17 (2022), CSSE-016 Q11 (2021).', 2, 'wave3-mr03-mixed-perimeter',
 'mr03-mixed-perimeter', 'angel_original', 'provisional', 1, true, 'Using the area value directly as part of the perimeter calculation, or forgetting to double the sum of both sides.',
 'MIXED_TRANSFER', array['MR-01']),

('mr03-mix-03', 'maths', 'QT-MR-07', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr03-mix-03","marks":1,"skill":"geometry","answer":"36m","question":"A rectangular lawn has an area of 45 m² and one side is 15m. What is the perimeter?","workingSteps":["The other side is 45 ÷ 15 = 3m","Perimeter = 2 × (15 + 3) = 36m"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-07, primary competency MR-03, supporting MR-01. Structure: MULTI-STEP APPLICATION. Transfer class: MIXED_TRANSFER. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q7/Q12 (2023), CSSE-011 Q12/Q17 (2022), CSSE-016 Q11 (2021).', 2, 'wave3-mr03-mixed-perimeter',
 'mr03-mixed-perimeter', 'angel_original', 'provisional', 1, true, 'Using the area value directly as part of the perimeter calculation, or forgetting to double the sum of both sides.',
 'MIXED_TRANSFER', array['MR-01']),

('mr04-far-04', 'maths', 'QT-MR-04', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr04-far-04","marks":1,"skill":"arithmetic","answer":"300g","question":"A recipe for 8 people uses 200g of flour. Using the same recipe, how much flour is needed for 12 people?","workingSteps":["200g ÷ 8 people = 25g per person","25g × 12 people = 300g"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-04, primary competency MR-04, supporting MR-01. Structure: CONTEXTUAL PROBLEM SOLVING. Transfer class: FAR_TRANSFER. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q1/Q13 (2023), CSSE-011 Q1/Q2/Q3 (2022), CSSE-016 Q1/Q2 (2021).', 2, 'wave3-mr04-far-recipe',
 'mr04-far-recipe', 'angel_original', 'provisional', 1, true, 'Adding or subtracting a fixed amount for the difference in people instead of scaling the whole recipe proportionally.',
 'FAR_TRANSFER', array['MR-01']),

('mr04-far-05', 'maths', 'QT-MR-04', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr04-far-05","marks":1,"skill":"arithmetic","answer":"270g","question":"A recipe for 6 people uses 180g of sugar. Using the same recipe, how much sugar is needed for 9 people?","workingSteps":["180g ÷ 6 people = 30g per person","30g × 9 people = 270g"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-04, primary competency MR-04, supporting MR-01. Structure: CONTEXTUAL PROBLEM SOLVING. Transfer class: FAR_TRANSFER. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q1/Q13 (2023), CSSE-011 Q1/Q2/Q3 (2022), CSSE-016 Q1/Q2 (2021).', 2, 'wave3-mr04-far-recipe',
 'mr04-far-recipe', 'angel_original', 'provisional', 1, true, 'Adding or subtracting a fixed amount for the difference in people instead of scaling the whole recipe proportionally.',
 'FAR_TRANSFER', array['MR-01']),

('mr04-far-06', 'maths', 'QT-MR-04', array['csse'], 'medium', 'short-answer', 60,
 $json${"id":"mr04-far-06","marks":1,"skill":"arithmetic","answer":"160g","question":"A recipe for 5 people uses 100g of butter. Using the same recipe, how much butter is needed for 8 people?","workingSteps":["100g ÷ 5 people = 20g per person","20g × 8 people = 160g"]}$json$,
 'Educational Increment 006, Wave 3. Assessment Brain QT-MR-04, primary competency MR-04, supporting MR-01. Structure: CONTEXTUAL PROBLEM SOLVING. Transfer class: FAR_TRANSFER. Deterministically generated by scripts/generate-mathematics-wave3.mjs and validated for duplicate id/question/answer before authoring. Real evidence basis: CSSE-006 Q1/Q13 (2023), CSSE-011 Q1/Q2/Q3 (2022), CSSE-016 Q1/Q2 (2021).', 2, 'wave3-mr04-far-recipe',
 'mr04-far-recipe', 'angel_original', 'provisional', 1, true, 'Adding or subtracting a fixed amount for the difference in people instead of scaling the whole recipe proportionally.',
 'FAR_TRANSFER', array['MR-01'])

on conflict (id) do nothing;

commit;
