-- Angel Digital 11+ — Migration 055
-- Educational Increment 007G — First Reviewed Content Activation.
--
-- Promotes exactly the 60 questions and 1 passage
-- covered by the 7 pilot targets' independent educational review
-- (all 7 decided 'approved', reviewer: Ayobami Lawal, per the Founder's
-- authenticated Supabase Table Editor inspection of ali_family_review --
-- that table remains RLS-opaque to every script/anon-key path in this
-- repository by design, migration 034/054, so this migration records
-- the Founder-supplied decision as its input, not a re-derivation).
--
-- Generated by scripts/generate-pilot-activation-migration.mjs, which
-- re-verified content_version, provenance, active state and
-- eligibility_status for every row against live production immediately
-- before this file was written, reusing checkActivationEligibility()
-- unchanged from scripts/generate-activation-migration.mjs (007E). 0
-- rows were excluded from the 60 questions live in the 6 approved
-- families at generation time.
--
-- wave2-eng-surprise's 4 attached questions (w2-surprise-01/02/03/04)
-- are each already included via their own family's membership above;
-- this migration additionally promotes the passage row itself
-- (ali_passage_bank), satisfying the dual-review dependency (a
-- Surprise-passage question requires both its family AND the passage
-- approved -- both are, for this pilot).
--
-- ali_passage_bank's own pre-activation gate (content_version,
-- provenance, active, still-provisional) could NOT be independently
-- re-verified by this script's anon key -- that table is RLS-opaque to
-- every anon-key path in this repository by design (migration 054,
-- Decision 48). The passage is included on documented evidence instead:
-- migration 051 inserted this row in the same atomic transaction as its
-- 4 questions (confirmed live and unchanged), no other write path to
-- this row has ever existed, and the Founder's own review explicitly
-- covered this passage. This is disclosed, not silently assumed.
--
-- Idempotent: only rows still 'provisional' are updated in each table,
-- so re-running this file after it has already taken effect is a no-op.
-- No row outside this named set is touched. Nothing is set to
-- mock_eligible or independently_validated.
--
-- Run this in: Supabase Dashboard > SQL Editor > New query.

begin;

update public.ali_question_bank
set eligibility_status = 'practice_eligible'
where id in ('w2-morningpatrol-08', 'w2-longwalk-02', 'w2-stormwarning-02', 'w2-surprise-02', 'w2-twoletters-07', 'w2-pianorecital-07', 'w1-kitemaker-06', 'w1-lastbus-06', 'w1-newgirl-06', 'w1-atticdoor-06', 'w1-raceday-06', 'w1-letter-06', 'w2-lastslice-06', 'w2-morningpatrol-02', 'w2-morningpatrol-03', 'w2-twoletters-06', 'w2-longwalk-03', 'w2-stormwarning-03', 'w2-surprise-04', 'w2-sciencefair-07', 'w2-stormwarning-07', 'w1-kitemaker-05', 'w1-lastbus-05', 'w1-newgirl-05', 'w1-atticdoor-05', 'w1-raceday-05', 'w1-letter-05', 'w2-morningpatrol-06', 'w2-understudy-04', 'w2-twoletters-05', 'w2-longwalk-06', 'w2-stormwarning-05', 'w2-pianorecital-05', 'w2-longwalk-07', 'w1-raceday-04', 'w2-lastslice-02', 'w2-twoletters-02', 'w2-sciencefair-02', 'w2-surprise-01', 'w2-sciencefair-06', 'w1-kitemaker-02', 'w1-lastbus-02', 'w1-newgirl-02', 'w1-atticdoor-02', 'w1-raceday-02', 'w1-letter-02', 'w2-lastslice-03', 'w2-morningpatrol-04', 'w2-understudy-02', 'w2-twoletters-03', 'w2-longwalk-04', 'w2-sciencefair-03', 'w2-stormwarning-04', 'w2-pianorecital-02', 'w2-surprise-03', 'w2-twoletters-08', 'w2-understudy-07', 'mr02-cmp-01', 'mr02-cmp-02', 'mr02-cmp-03')
  and eligibility_status = 'provisional';

update public.ali_passage_bank
set eligibility_status = 'practice_eligible'
where id = 'wave2-eng-surprise'
  and eligibility_status = 'provisional';

commit;
