-- Angel Digital 11+ — Migration 056
-- Educational Increment 007H — Controlled Review Batch 2 Activation.
--
-- Promotes exactly the 45 questions covered by the 6
-- Batch 2 targets' independent educational review (all 6 decided
-- 'approved', reviewer: Ayobami Lawal, per the Founder's authenticated
-- Supabase Table Editor inspection of ali_family_review -- that table
-- remains RLS-opaque to every script/anon-key path in this repository by
-- design, migration 034/054, so this migration records the Founder-
-- supplied decision as its input, not a re-derivation).
--
-- Generated by scripts/generate-batch2-activation-migration.mjs, which
-- re-verified content_version, provenance, active state and
-- eligibility_status for every row against live production immediately
-- before this file was written, reusing checkActivationEligibility()
-- unchanged from scripts/generate-activation-migration.mjs (007E). 0
-- rows were excluded from the 45 questions live in the 6 approved
-- families at generation time.
--
-- No passage is touched by this migration: none of Batch 2's 6 families
-- carries the passage-promotion dependency 007G's two-character/
-- multiselect families did (ANGEL_007H_BATCH2_SELECTION_V1.md Part 1).
--
-- Idempotent: only rows still 'provisional' are updated, so re-running
-- this file after it has already taken effect is a no-op. No row outside
-- this named set is touched. Nothing is set to mock_eligible or
-- independently_validated. No content, answer, or family_id is changed.
-- ali_family_review (review history) is not touched by this migration.
--
-- Run this in: Supabase Dashboard > SQL Editor > New query.

begin;

update public.ali_question_bank
set eligibility_status = 'practice_eligible'
where id in ('w1-atticdoor-01', 'w1-kitemaker-01', 'w1-lastbus-01', 'w1-letter-01', 'w1-newgirl-01', 'w1-raceday-01', 'w2-lastslice-01', 'w2-longwalk-01', 'w2-morningpatrol-01', 'w2-pianorecital-01', 'w2-sciencefair-01', 'w2-stormwarning-01', 'w2-twoletters-01', 'w2-understudy-01', 'w1-atticdoor-03', 'w1-kitemaker-03', 'w1-lastbus-03', 'w1-letter-03', 'w1-newgirl-03', 'w1-raceday-03', 'w2-lastslice-04', 'w2-longwalk-05', 'w2-morningpatrol-05', 'w2-pianorecital-03', 'w2-understudy-03', 'w1-atticdoor-07', 'w1-kitemaker-07', 'w1-lastbus-07', 'w1-letter-07', 'w1-newgirl-07', 'w1-raceday-07', 'w2-lastslice-07', 'w2-pianorecital-06', 'w2-sciencefair-05', 'w2-stormwarning-06', 'w2-understudy-06', 'mr03-cls-01', 'mr03-cls-02', 'mr03-cls-03', 'mr04-far-01', 'mr04-far-02', 'mr04-far-03', 'mr04-mix-01', 'mr04-mix-02', 'mr04-mix-03')
  and eligibility_status = 'provisional';

commit;
