-- Angel Digital 11+ — Migration 057
-- Educational Increment 007J — Controlled Review Batch 3 Activation.
--
-- Promotes exactly the 30 questions covered by the 7
-- Batch 3 targets' independent educational review (all 7 decided
-- 'approved', reviewer: Ayobami Lawal, per the Founder's authenticated
-- Supabase Table Editor inspection of ali_family_review -- that table
-- remains RLS-opaque to every script/anon-key path in this repository by
-- design, migration 034/054, so this migration records the Founder-
-- supplied decision as its input, not a re-derivation).
--
-- Generated by scripts/generate-batch3-activation-migration.mjs, which
-- re-verified content_version, provenance, active state and
-- eligibility_status for every row against live production immediately
-- before this file was written, reusing checkActivationEligibility()
-- unchanged from scripts/generate-activation-migration.mjs (007E). 0
-- rows were excluded from the 30 questions live in the 7 approved
-- families at generation time -- the full 30-question ceiling passed
-- every gate.
--
-- No passage is touched by this migration: all 7 Batch 3 families are
-- Mathematics question families with no passage dependency.
--
-- Idempotent: only rows still 'provisional' are updated, so re-running
-- this file after it has already taken effect is a no-op. No row outside
-- this named set is touched. Nothing is set to mock_eligible or
-- independently_validated. No content, answer, or family_id is changed.
-- ali_family_review (review history) is not touched by this migration.
--
-- Run this in: Supabase Dashboard > SQL Editor > New query.

begin;

update public.ali_question_bank
set eligibility_status = 'practice_eligible'
where id in ('mr01-mop-01', 'mr01-mop-02', 'mr01-mop-03', 'mr01-mop-04', 'mr03-coord-01', 'mr03-coord-02', 'mr03-coord-03', 'mr01-conv-01', 'mr01-conv-02', 'mr01-conv-03', 'mr01-conv-04', 'mr01-data-01', 'mr01-data-02', 'mr01-data-03', 'mr01-data-04', 'mr01-data-05', 'mr04-time-01', 'mr04-time-02', 'mr04-time-03', 'mr04-time-04', 'mr04-time-05', 'mr01-mean-01', 'mr01-mean-02', 'mr01-mean-03', 'mr01-mean-04', 'mr02-nth-01', 'mr02-nth-02', 'mr02-nth-03', 'mr02-nth-04', 'mr02-nth-05')
  and eligibility_status = 'provisional';

commit;
