-- Angel Digital 11+ — Migration 058
-- Educational Increment 007K — Controlled Review Batch 4 Activation.
--
-- Promotes exactly the 37 questions covered by the 9
-- Batch 4 targets' independent educational review (all 9 decided
-- 'approved', reviewer: Ayobami Lawal, per the Founder's authenticated
-- Supabase Table Editor inspection of ali_family_review -- that table
-- remains RLS-opaque to every script/anon-key path in this repository by
-- design, migration 034/054, so this migration records the Founder-
-- supplied decision as its input, not a re-derivation -- see Decision 56,
-- ALI_DECISION_LOG.md).
--
-- Generated by scripts/generate-batch4-activation-migration.mjs, which
-- re-verified content_version, provenance, active state and
-- eligibility_status for every row against live production immediately
-- before this file was written, reusing checkActivationEligibility()
-- unchanged from scripts/generate-activation-migration.mjs (007E). 0
-- rows were excluded from the 37 questions live in the 9 approved
-- families at generation time -- the full 37-question ceiling passed
-- every gate.
--
-- Two of the 9 families (mr03-mixed-perimeter, mr04-far-recipe) were
-- affected by Decision 55's Mathematics unit-answer validation defect.
-- That defect is fixed, deployed, and independently re-verified (21
-- direct tests + a 166-check bank-wide regression) before this migration
-- was generated -- see Decision 55 and Decision 56.
--
-- No passage is touched by this migration: all 9 Batch 4 families are
-- Mathematics question families with no passage dependency.
--
-- Idempotent: only rows still 'provisional' are updated, so re-running
-- this file after it has already taken effect is a no-op. No row outside
-- this named set is touched. Nothing is set to mock_eligible or
-- independently_validated. No content, answer, or family_id is changed.
-- ali_family_review (review history) is not touched by this migration.
--
-- Run this in: Supabase Dashboard > SQL Editor > New query.

begin;

update public.ali_question_bank
set eligibility_status = 'practice_eligible'
where id in ('mr04-bv-01', 'mr04-bv-02', 'mr04-bv-03', 'mr04-bv-04', 'mr04-bv-05', 'mr02-far-01', 'mr02-far-02', 'mr02-far-03', 'mr05-fp-01', 'mr05-fp-02', 'mr05-fp-03', 'mr05-fp-04', 'mr05-fp-05', 'mr05-mult-01', 'mr05-mult-02', 'mr05-mult-03', 'mr03-angratio-01', 'mr03-angratio-02', 'mr03-angratio-03', 'mr03-angratio-04', 'mr03-angratio-05', 'mr02-sumdiff-01', 'mr02-sumdiff-02', 'mr02-sumdiff-03', 'mr02-sumdiff-04', 'mr02-sumdiff-05', 'mr04-cpct-01', 'mr04-cpct-02', 'mr04-cpct-03', 'mr04-cpct-04', 'mr04-cpct-05', 'mr03-mix-01', 'mr03-mix-02', 'mr03-mix-03', 'mr04-far-04', 'mr04-far-05', 'mr04-far-06')
  and eligibility_status = 'provisional';

commit;
