-- Angel Digital 11+ — Migration 065
-- Educational Increment 007T — Final Review Reconciliation and Controlled
-- Activation.
--
-- Promotes exactly the 34 questions covered by the 6
-- approved 007T question-family targets' independent educational review
-- (all 11 007T targets — 6 question families + 5 passages — decided
-- 'approved', reviewer: Ayobami Lawal, one historical row spelled "Ayobami
-- Lawl" — a disclosed data-entry typo, not a different reviewer or
-- invalid evidence — per the Founder's authenticated Supabase Table
-- Editor inspection of ali_family_review -- that table remains RLS-opaque
-- to every script/anon-key path in this repository by design, migration
-- 034/054, so this migration records the Founder-supplied decision as
-- its input, not a re-derivation -- see Decision 73, ALI_DECISION_LOG.md).
--
-- Generated by scripts/generate-007t-activation-migration.mjs, which
-- re-verified content_version, provenance, active state and
-- eligibility_status for every row against live production immediately
-- before this file was written, reusing checkActivationEligibility()
-- unchanged from scripts/generate-activation-migration.mjs (007E).
--
-- SCOPED TO QUESTIONS ONLY. The 5 approved passages
-- (wave3-eng-emptyclassroom, wave3-eng-bakersapprentice,
-- wave3-eng-lettertograndad, wave3-eng-stormharbour, wave3-eng-newtrainers)
-- are deliberately NOT touched: every one of the 14 English question rows
-- below carries its own self-contained copy of its passage's text
-- (prompt.passageText/prompt.passageTitle), confirmed against live
-- production, so Practice does not depend on ali_passage_bank's own
-- eligibility_status to display or complete these questions correctly.
-- Passage activation, if wanted, is a separate, not-yet-authorised
-- decision.
--
-- Teaching-maturity boundary (unchanged, not claimed by this migration):
-- the 4 new Mathematics families' PRACTICE content is Founder-approved by
-- this migration; their dedicated MODEL/Guided teaching architecture has
-- NOT been authored (007T Part 10 / 007U's own disclosure) and this
-- migration does not, and cannot, change that. The 2 English families use
-- only the existing question-row modelAnswer convention, already
-- technically supported -- no teaching content is manufactured here.
--
-- Idempotent: only rows still 'provisional' are updated, so re-running
-- this file after it has already taken effect is a no-op. No row outside
-- this named set is touched. Nothing is set to mock_eligible. No content,
-- answer, family_id, provenance, or content_version is changed.
-- ali_family_review (review history) is not touched by this migration.
-- ali_passage_bank is not touched by this migration.
--
-- Run this in: Supabase Dashboard > SQL Editor > New query.

begin;

update public.ali_question_bank
set eligibility_status = 'practice_eligible'
where id in ('mr01-wholenum-01', 'mr01-wholenum-02', 'mr01-wholenum-03', 'mr01-wholenum-04', 'mr01-wholenum-05', 'mr01-decimal-01', 'mr01-decimal-02', 'mr01-decimal-03', 'mr01-decimal-04', 'mr01-decimal-05', 'mr01-fraction-01', 'mr01-fraction-02', 'mr01-fraction-03', 'mr01-fraction-04', 'mr01-fraction-05', 'mr01-multistep-01', 'mr01-multistep-02', 'mr01-multistep-03', 'mr01-multistep-04', 'mr01-multistep-05', 'w3-rc10-am-01', 'w3-rc10-am-02', 'w3-rc10-am-03', 'w3-rc10-am-04', 'w3-rc10-am-05', 'w3-rc10-am-06', 'w3-rc10-wc-01', 'w3-rc10-wc-02', 'w3-rc10-wc-03', 'w3-rc10-wc-04', 'w3-rc10-wc-05', 'w3-rc10-wc-06', 'w3-rc10-wc-07', 'w3-rc10-wc-08')
  and eligibility_status = 'provisional';

commit;
