-- Angel Digital 11+ — Migration 068
-- Educational Increment 007X — Founder Review, Controlled Activation and
-- Final Closure.
--
-- Promotes exactly the 14 questions covered by the 4 approved
-- 007X question-family review targets (mr05-number-property-search,
-- mr03-mixed-perimeter, precision-frac, precision-dec), all decided
-- 'approved', reviewer: Founder — per the Founder's authenticated
-- Supabase inspection of ali_family_review (that table remains RLS-opaque
-- to every script/anon-key path in this repository by design, migration
-- 034/054, so this migration records the Founder-supplied decision as its
-- input, not a re-derivation — see Decisions 79/80/81, ALI_DECISION_LOG.md).
--
-- Disclosed: the authenticated evidence contained 3 duplicate "new 007X
-- Founder decision" rows for mr05-number-property-search (identical scope,
-- same 5 question IDs) — treated as one Founder decision recorded 3 times
-- in append-only history, not 3 independent reviews. None were deleted or
-- rewritten.
--
-- Generated by scripts/generate-007x-activation-migration.mjs, which
-- re-verified content_version, provenance, active state and
-- eligibility_status for every row against live production immediately
-- before this file was written, reusing checkActivationEligibility()
-- unchanged from scripts/generate-activation-migration.mjs (007E).
--
-- Selected by exact question ID, never by family_id: mth-003 (reclassified
-- into mr03-mixed-perimeter by migration 066, metadata only) is NOT one of
-- the 14 newly authored questions the Founder's review covered, and is
-- deliberately excluded — its own eligibility_status is untouched by this
-- migration. No other historical sibling in any of the 4 families is
-- touched either.
--
-- Teaching-maturity / transfer-classification boundary (unchanged, not
-- claimed by this migration): mr05-number-property-search's PRACTICE
-- content is Founder-approved by this migration; its TRANSFER-UNSAFE
-- classification and the absence of dedicated MODEL/Guided teaching
-- content are UNCHANGED — approval of these 5 new questions does not
-- itself revalidate transfer safety or teaching maturity.
--
-- Idempotent: only rows still 'provisional' are updated, so re-running
-- this file after it has already taken effect is a no-op. No row outside
-- this named set is touched. Nothing is set to mock_eligible. No content,
-- answer, family_id, provenance, or content_version is changed.
-- ali_family_review (review history) is not touched by this migration.
--
-- Fails safely: if fewer than 14 of the named IDs are currently
-- 'provisional' (already activated elsewhere, or missing), this UPDATE
-- simply affects fewer rows rather than erroring — re-run
-- scripts/generate-007x-activation-migration.mjs to re-verify the exact
-- candidate set against live production before applying if that is ever
-- suspected.
--
-- Run this in: Supabase Dashboard > SQL Editor > New query.

begin;

update public.ali_question_bank
set eligibility_status = 'practice_eligible'
where id in ('mr05-search-03', 'mr05-search-04', 'mr05-search-05', 'mr05-search-06', 'mr05-search-07', 'mr03-mix-04', 'mr03-mix-05', 'mr03-mix-06', 'precision-frac-04', 'precision-frac-05', 'precision-frac-06', 'precision-dec-04', 'precision-dec-05', 'precision-dec-06')
  and eligibility_status = 'provisional';

commit;
