-- Angel Digital 11+ — Migration 080
-- Stage 3, Increment 005 — Independently Approved MR-04 Content Activation.
--
-- Promotes exactly the 11 questions covered by the 3 approved
-- Stage 3 MR-04 Content Depth Review targets (mr04-reverse-percentage,
-- mr04-time-reverse, mr04-bv-convert), all decided 'approved', reviewer:
-- Founder — per the Founder's authenticated Supabase inspection of
-- ali_family_review (that table remains RLS-opaque to every script/anon-key
-- path in this repository by design, migration 034/054, so this migration
-- records the Founder-supplied decision as its input, not a re-derivation —
-- see ALI_DECISION_LOG.md Decisions 79-81, 117, 118).
--
-- Generated by scripts/generate-mr04-depth-activation-migration.mjs, which
-- re-verified content_version, provenance, active state and
-- eligibility_status for every row against live production immediately
-- before this file was written, reusing checkActivationEligibility()
-- unchanged from scripts/generate-activation-migration.mjs (007E).
--
-- Selected by exact question ID, never by family_id: no other row in any
-- of the 3 families is touched, and no future sibling added later to any
-- of these families could ever be silently swept into this activation.
--
-- Content-depth boundary (unchanged, not claimed by this migration): this
-- migration activates these 11 questions for canonical Practice. It does
-- not solve Mathematics' wider zero-parameter-variation problem (Decision
-- 116/117), and does not claim these 11 rows are 11 fully independent
-- novel experiences — Decision 117's own finding (approximately six
-- genuinely distinct scenario shapes across the 11 rows) is preserved,
-- not superseded, by activation.
--
-- Idempotent: only rows still 'provisional' are updated, so re-running
-- this file after it has already taken effect is a no-op. No row outside
-- this named set is touched. Nothing is set to mock_eligible. No content,
-- answer, working step, misconception, difficulty, family_id, provenance,
-- or content_version is changed. ali_family_review (review history) is
-- not touched by this migration.
--
-- Fails safely: if fewer than 11 of the named IDs are currently
-- 'provisional' (already activated elsewhere, or missing), this UPDATE
-- simply affects fewer rows rather than erroring — re-run
-- scripts/generate-mr04-depth-activation-migration.mjs to re-verify the
-- exact candidate set against live production before applying if that is
-- ever suspected.
--
-- NOT APPLIED. Run this in: Supabase Dashboard > SQL Editor > New query.

begin;

update public.ali_question_bank
set eligibility_status = 'practice_eligible'
where id in ('mr04-revpct-01', 'mr04-revpct-02', 'mr04-revpct-03', 'mr04-revpct-04', 'mr04-timerev-01', 'mr04-timerev-02', 'mr04-timerev-03', 'mr04-timerev-04', 'mr04-bvconv-01', 'mr04-bvconv-02', 'mr04-bvconv-03')
  and eligibility_status = 'provisional';

commit;
