-- Angel Digital 11+ — Migration 083
-- Stage 3, Increment 007 — Controlled Activation of Approved Mathematics
-- Structural Depth Content.
--
-- Promotes exactly the 8 questions covered by the 2 approved
-- Stage 3 Mathematics Structural Depth Review targets (mr01-reverse-mean,
-- mr03-coord-combined), both decided 'approved', reviewer: Founder —
-- per the Founder's authenticated Supabase inspection of ali_family_review
-- (that table remains RLS-opaque to every script/anon-key path in this
-- repository by design, migration 034/054, independently re-confirmed
-- this increment, so this migration records the Founder-supplied decision
-- as its input, not a re-derivation — see ALI_DECISION_LOG.md Decisions
-- 79-81, 117-119, 121-122).
--
-- Generated by scripts/generate-inc006-depth-activation-migration.mjs,
-- which re-verified content_version, provenance, active state and
-- eligibility_status for every row against live production immediately
-- before this file was written, reusing checkActivationEligibility()
-- unchanged from scripts/generate-activation-migration.mjs (007E).
--
-- Selected by exact question ID, never by family_id: no other row in
-- either family is touched, and no future sibling added later to either
-- family could ever be silently swept into this activation.
--
-- Content-depth boundary (unchanged, not claimed by this migration): this
-- migration activates these 8 questions for canonical Practice. It does
-- not solve Mathematics' wider zero-parameter-variation problem (Decision
-- 116/117 Conclusion B, still open), and does not claim mr01-reverse-mean's
-- 4 rows are 4 fully independent novel experiences -- Decision 122's own
-- finding (one shared reverse-mean reasoning structure across all 4) is
-- preserved, not superseded, by activation. mr03-coord-combined's 4 rows
-- remain 4 genuinely distinct combined-transformation experiences.
--
-- Idempotent: only rows still 'provisional' are updated, so re-running
-- this file after it has already taken effect is a no-op. No row outside
-- this named set is touched. Nothing is set to mock_eligible. No content,
-- answer, working step, misconception, difficulty, family_id, provenance,
-- or content_version is changed. ali_family_review (review history) is
-- not touched by this migration.
--
-- Fails safely: if fewer than 8 of the named IDs are currently
-- 'provisional' (already activated elsewhere, or missing), this UPDATE
-- simply affects fewer rows rather than erroring — re-run
-- scripts/generate-inc006-depth-activation-migration.mjs to re-verify the
-- exact candidate set against live production before applying if that is
-- ever suspected.
--
-- NOT APPLIED. Run this in: Supabase Dashboard > SQL Editor > New query.

begin;

update public.ali_question_bank
set eligibility_status = 'practice_eligible'
where id in ('mr01-revmean-01', 'mr01-revmean-02', 'mr01-revmean-03', 'mr01-revmean-04', 'mr03-combo-01', 'mr03-combo-02', 'mr03-combo-03', 'mr03-combo-04')
  and eligibility_status = 'provisional';

commit;
