-- Angel Digital 11+ — Migration 151
-- Mathematics Mock 1 — Deterministic Mock Analysis Engine (Decision 223).
--
-- ============================================================
-- WHY THIS MIGRATION EXISTS
-- ============================================================
-- Decision 222 found: no Mock analysis processor exists anywhere to
-- wire up (`analysis_state` has never left `not_started`, migration 072
-- reserved it explicitly for "a future scoring/analysis increment"); the
-- closest existing thing (`lib/learningEngine/rollup.ts`) is the wrong
-- tool, deliberately walled off from Mock evidence by migration 074's
-- own architecture (never feed Mock outcomes into
-- `ali_student_question_history`, so a high Mock score can never
-- silently make a competency "mastered"); and `ali_question_bank`
-- already carries real, human-authored `addresses_misconception` and
-- `prompt.workingSteps` content for the Mock 1 pool, sampled across
-- three separate content-authoring eras. This migration builds the
-- SMALLEST deterministic engine that turns a SCORED attempt's own
-- `question_outcomes` (already stored, migration 104) plus a live join
-- to `ali_question_bank` into trustworthy, evidence-bounded per-skill
-- feedback -- never a competency mastery claim, never a specific
-- misconception diagnosis, never a full-answer reveal.
--
-- ============================================================
-- THE CHANGE: three new, additive, nullable columns; one new function;
-- one redefined trigger function (no trigger DDL change)
-- ============================================================
-- `ali_mock_attempt_report.skill_evidence jsonb` -- the full per-skill
-- evidence array plus a small, deterministic next-practice priority
-- list (shape documented in `lib/mockAttempt/types.ts`'s own
-- `MockSkillEvidence`). `analysis_version integer` -- mirrors
-- `marking_version`'s own existing idempotency pattern exactly.
-- `analysed_at timestamptz` -- mirrors `released_at`'s own existing
-- pattern exactly. All three NULL for every existing row and for any
-- attempt this engine has not yet processed.
--
-- `mock_analyse_attempt(p_attempt_id uuid)` -- SECURITY DEFINER,
-- re-derives identity from `auth.uid()` exactly like `mock_score_
-- attempt()` (migration 075) already does even though its own real
-- caller is the trigger below, not a direct RPC call -- the SAME
-- defense-in-depth precedent, not a new pattern. Granted to NO role at
-- all, from the start (never `authenticated`, never `anon`) -- the
-- lesson migration 074/075's own two-step grant-then-revoke history
-- already taught this codebase, applied correctly from the first line
-- here rather than repeated. Preconditions: the caller's own attempt;
-- `ali_mock_attempt_report.scoring_state = 'scored'` (a manual-marking-
-- pending attempt, `scoring_state = 'scoring'`, is never analysed --
-- there is nothing yet to safely aggregate). Idempotent per
-- `analysis_version`: a second call at the same version, once already
-- `analysis_state = 'complete'`, is a no-op, matching `mock_score_
-- attempt()`'s own established idempotency check exactly.
--
-- EVIDENCE CONTRACT (Decision 223's own governing rule, enforced in
-- code, not merely documented): OBSERVED evidence is `question_
-- outcomes[].status/marksAwarded/marksAvailable/questionTypeId`
-- (already stored by `mock_score_attempt()`, untouched by this
-- migration). DERIVED evidence is this function's own per-skill
-- aggregation (marks achieved/available, subpart count, correct count,
-- difficulty distribution, percentage) -- pure arithmetic over OBSERVED
-- rows, no invented weighting. AUTHORED EDUCATIONAL EVIDENCE is
-- `ali_question_bank.addresses_misconception`/`content_difficulty`,
-- read live per question -- pre-existing, previously-reviewed content,
-- never generated by this function. A skill is classified
-- `demonstrated_securely` only when EVERY observed subpart is correct
-- AND at least 2 subparts were observed; `not_yet_demonstrated` when
-- ALL observed subparts (2+) are incorrect/unanswered; `developing`
-- when 2+ subparts are observed with a mixed result; `insufficient_
-- evidence` whenever fewer than 2 subparts were observed for that
-- skill, REGARDLESS of correctness -- a single one-mark question can
-- never alone produce a strength or a development-area claim. This
-- symmetric, disclosed, minimum-2-observations threshold is a Decision-
-- 223 convention, not sourced from any existing specification -- named
-- explicitly as such, matching this codebase's own established
-- discipline (`rollup.ts`'s own comment: "no invented weighting
-- constants") of never silently inventing an unstated rule.
--
-- MISCONCEPTION SAFETY (Decision 222 Part 8 / this task's own explicit
-- instruction): `addresses_misconception` describes a misconception the
-- QUESTION is designed to diagnose, never a claim about what the
-- learner actually did. No deterministic matching exists between a
-- learner's free-text/numeric response and a specific misconception
-- pattern -- none is invented here. `misconceptionNotes` are attached
-- to a skill only from INCORRECT rows, and only ever surfaced in the
-- SAFE, question-designed framing ("this question type often
-- involves..."), never "you made the mistake of...". `strengths`/
-- `weaknesses` reuse the exact, pre-existing `MockStrengthOrPriorityEntry`
-- shape (migration 072) -- no new column needed for either.
--
-- QUESTION REVIEW BOUNDARY (Decision 222 Part 8, held, not weakened):
-- this function never reads or stores `prompt.workingSteps`, the stored
-- correct answer, or the learner's own response text anywhere in
-- `skill_evidence`/`strengths`/`weaknesses`/`competency_evidence` --
-- confirmed structurally by this migration's own accompanying test
-- suite. No question-retirement/reuse-tracking mechanism exists yet
-- (Decision 222 Part 8's own named prerequisite) -- this migration does
-- not add one, and does not need one, precisely because it never
-- exposes a full answer.
--
-- TRIGGER REDEFINITION (`mock_attempt_report_init()`, migration 072,
-- redefined 075, redefined again here -- same trigger object, migration
-- 072's own `mock_attempt_report_init_trigger`, unmodified, no DDL
-- change needed): after `mock_score_attempt()`'s own existing, unchanged
-- nested exception block, a SECOND, entirely independent nested
-- exception block calls `mock_analyse_attempt()` -- but ONLY when
-- scoring just succeeded (`scoring_state = 'scored'`, re-read fresh
-- from the row, never assumed). A failure inside this second block sets
-- `analysis_state = 'failed'` and NOTHING else -- it can never touch
-- `scoring_state`, `question_outcomes`, or `overall`, and it can never
-- roll back `mock_submit_attempt()`'s own already-committed submission,
-- for the exact same structural reason migration 075's own scoring
-- block already can't: each `begin...exception...end` block is its own
-- isolated sub-transaction-like unit inside PL/pgSQL, and this one
-- updates a disjoint set of columns from the scoring block.
--
-- ============================================================
-- WHAT THIS MIGRATION DOES NOT DO
-- ============================================================
-- Does not change the Mathematics Mock 1 composition, 21-question/56-
-- mark manifest, activation state, `mock_score_attempt()`'s own body,
-- the timer, resume, question eligibility, or any content wording --
-- confirmed by this migration's own test suite asserting `mock_score_
-- attempt` is never redefined here. Does not populate `competency_
-- evidence` into `ali_student_question_history` or call `processEvidence
-- ForCompetency()` -- migration 074's own provenance-isolation wall
-- stands, untouched. Does not expose full correct answers, `working
-- Steps`, or mark-scheme detail to any learner. Does not build question
-- retirement tracking. Does not touch Learning Report, Parent Dashboard,
-- Progress Timeline, Admissions Readiness, or Weekly Report. Does not
-- add a queue, cron, or any process outside this database's own existing
-- trigger mechanism. Does not create an `ali_mock_attempt` row or call
-- `mock_create_attempt()`/`mock_create_cycle_attempt()`.
--
-- NOT APPLIED. Generated for Founder review and manual application via
-- Supabase Dashboard > SQL Editor > New query, after migrations 070-150
-- (all Founder-confirmed applied, per this arc's own standing record)
-- have already been applied.

begin;

-- === Additive columns ===================================================

alter table public.ali_mock_attempt_report
  add column if not exists skill_evidence jsonb;

alter table public.ali_mock_attempt_report
  add column if not exists analysis_version integer;

alter table public.ali_mock_attempt_report
  add column if not exists analysed_at timestamptz;

comment on column public.ali_mock_attempt_report.skill_evidence is
  'Decision 223 -- deterministic per-skill evidence: { bySkill: [{competencyId, questionTypeId, marksAchieved, marksAvailable, percentage, subpartCount, correctCount, evidenceLevel, difficultyDistribution, misconceptionNotes}], nextPracticePriorities: [{competencyId, questionTypeId}] }. NULL until mock_analyse_attempt() populates it. Never contains a stored correct answer, workingSteps, or the learner''s own response text.';

comment on column public.ali_mock_attempt_report.analysis_version is
  'Decision 223 -- mirrors marking_version''s own existing idempotency pattern. NULL until analysed.';

comment on column public.ali_mock_attempt_report.analysed_at is
  'Decision 223 -- mirrors released_at''s own existing pattern. NULL until analysed.';

-- === Internal helper: mock_question_type_competency ====================
--
-- A small, deliberate, disclosed duplication of `lib/learningEngine/
-- assessmentBrainMap.ts`'s own `QUESTION_TYPE_PRIMARY_COMPETENCY` object
-- literal, reproduced here byte-for-byte -- not the general precedent
-- migration 104 established (which deliberately leaves questionTypeId
-- ->competency resolution to the client for `question_outcomes`, to
-- avoid duplicating a mapping SQL does not need). This ONE case is
-- different: `strengths`/`weaknesses` (migration 072) already committed,
-- before this decision existed, to a `competencyId: string` field (not
-- `questionTypeId`) as their own established type contract, already
-- consumed by the existing, tested `strengthSentence()`/`priorSentence()`
-- (Decision 216). Changing that contract now would mean touching
-- already-proven capability for a one-engine decision -- duplicating
-- this small (14-entry), stable, taxonomy-defining constant is the
-- smaller, safer choice, exactly mirroring this codebase's own
-- established tolerance for a disclosed, test-verified duplication when
-- the alternative is a wider blast radius (e.g. migration 104's own
-- disclosed `questionTypeId` in `question_outcomes` itself). Verified,
-- not merely asserted, by this migration's own accompanying test suite,
-- which asserts every entry here matches `assessmentBrainMap.ts`'s own
-- object literal exactly, so any future drift between the two is caught,
-- never silently diverges. Granted to no role -- an internal helper only,
-- callable exclusively from within mock_analyse_attempt()'s own
-- SECURITY DEFINER context, the same pattern mock_cycle_is_open()
-- (migration 107) already established for exactly this kind of helper.
create or replace function public.mock_question_type_competency(p_question_type_id text)
returns text
language sql
immutable
as $$
  select case p_question_type_id
    when 'QT-RC-01' then 'RC-01' when 'QT-RC-02' then 'RC-02' when 'QT-RC-03' then 'RC-03'
    when 'QT-RC-04' then 'RC-03' when 'QT-RC-05' then 'RC-02' when 'QT-RC-06' then 'RC-04'
    when 'QT-RC-07' then 'RC-01' when 'QT-RC-08' then 'RC-01' when 'QT-RC-09' then 'RC-01'
    when 'QT-RC-10' then 'RC-02' when 'QT-AR-01' then 'AR-01'
    when 'QT-WC-01a' then 'WC-01' when 'QT-WC-01b' then 'WC-01'
    when 'QT-MR-01' then 'MR-01' when 'QT-MR-02' then 'MR-01' when 'QT-MR-03' then 'MR-01'
    when 'QT-MR-04' then 'MR-04' when 'QT-MR-05' then 'MR-02' when 'QT-MR-06' then 'MR-02'
    when 'QT-MR-07' then 'MR-03' when 'QT-MR-08' then 'MR-03' when 'QT-MR-09' then 'MR-01'
    when 'QT-MR-10' then 'MR-04' when 'QT-MR-11' then 'MR-05' when 'QT-MR-12' then 'MR-01'
    when 'QT-MR-13' then 'MR-04' when 'QT-MR-14' then 'MR-06'
    else null
  end;
$$;

revoke all on function public.mock_question_type_competency(text) from public;

-- === Function: mock_analyse_attempt ====================================

create or replace function public.mock_analyse_attempt(p_attempt_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id uuid;
  v_attempt public.ali_mock_attempt;
  v_report public.ali_mock_attempt_report;
  v_current_analysis_version constant integer := 1;
  v_outcome jsonb;
  v_question_id text;
  v_status text;
  v_marks_awarded numeric;
  v_marks_available numeric;
  v_question_type_id text;
  v_bank_row public.ali_question_bank;
  v_skill_keys text[] := array[]::text[];
  v_skill_key text;
  -- Per-skill accumulator maps, keyed by questionTypeId, parallel arrays
  -- (PL/pgSQL has no native map type; this mirrors the same accumulation
  -- style mock_score_attempt() already uses for its own scalar totals).
  v_marks_achieved jsonb := '{}'::jsonb;
  v_marks_available_map jsonb := '{}'::jsonb;
  v_subpart_count jsonb := '{}'::jsonb;
  v_correct_count jsonb := '{}'::jsonb;
  v_difficulty_counts jsonb := '{}'::jsonb;
  v_misconceptions jsonb := '{}'::jsonb;
  v_by_skill jsonb := '[]'::jsonb;
  v_strengths jsonb := '[]'::jsonb;
  v_weaknesses jsonb := '[]'::jsonb;
  v_priorities jsonb := '[]'::jsonb;
  v_competency_evidence jsonb := '[]'::jsonb;
  v_evidence_level text;
  v_percentage numeric;
  v_skill_subparts integer;
  v_skill_correct integer;
  v_skill_achieved numeric;
  v_skill_available numeric;
  v_skill_difficulty jsonb;
  v_skill_misconceptions jsonb;
begin
  select id into v_profile_id from public.profiles where auth_user_id = auth.uid();

  select * into v_attempt from public.ali_mock_attempt
    where id = p_attempt_id and profile_id = v_profile_id;
  if not found then
    raise exception 'Attempt % not found for caller', p_attempt_id;
  end if;

  select * into v_report from public.ali_mock_attempt_report where attempt_id = p_attempt_id;
  if not found then
    raise exception 'No report row exists for attempt % -- the migration 072 report-init trigger should have created one on submission', p_attempt_id;
  end if;
  if v_report.scoring_state <> 'scored' then
    raise exception 'Attempt % report is not fully scored (scoring_state=%) -- analysis requires a fully-resolved score, never a manual-marking-pending one', p_attempt_id, v_report.scoring_state;
  end if;

  -- Idempotent: already analysed at the current analysis version -- no-op.
  if v_report.analysis_state = 'complete' and v_report.analysis_version = v_current_analysis_version then
    return;
  end if;

  -- === Pass 1: accumulate per-skill (questionTypeId) evidence from
  -- OBSERVED question_outcomes, joined live to ali_question_bank for
  -- AUTHORED EDUCATIONAL EVIDENCE (addresses_misconception, content_difficulty). ===
  for v_outcome in select * from jsonb_array_elements(coalesce(v_report.question_outcomes, '[]'::jsonb))
  loop
    v_question_id := v_outcome->>'questionId';
    v_status := v_outcome->>'status';
    v_question_type_id := v_outcome->>'questionTypeId';

    -- A row with no resolvable skill (manifest question no longer
    -- resolves to a bank row, or requires_manual_marking with no skill
    -- context) contributes no skill evidence -- never guessed.
    if v_question_type_id is null or v_status = 'requires_manual_marking' then
      continue;
    end if;

    v_marks_available := coalesce((v_outcome->>'marksAvailable')::numeric, 0);
    v_marks_awarded := coalesce((v_outcome->>'marksAwarded')::numeric, 0);

    select * into v_bank_row from public.ali_question_bank where id = v_question_id;

    if not (v_skill_keys @> array[v_question_type_id]) then
      v_skill_keys := v_skill_keys || v_question_type_id;
      v_marks_achieved := v_marks_achieved || jsonb_build_object(v_question_type_id, 0::numeric);
      v_marks_available_map := v_marks_available_map || jsonb_build_object(v_question_type_id, 0::numeric);
      v_subpart_count := v_subpart_count || jsonb_build_object(v_question_type_id, 0);
      v_correct_count := v_correct_count || jsonb_build_object(v_question_type_id, 0);
      v_difficulty_counts := v_difficulty_counts || jsonb_build_object(v_question_type_id, jsonb_build_object('easy', 0, 'medium', 0, 'hard', 0, 'challenge', 0));
      v_misconceptions := v_misconceptions || jsonb_build_object(v_question_type_id, '[]'::jsonb);
    end if;

    v_marks_achieved := jsonb_set(v_marks_achieved, array[v_question_type_id], to_jsonb((v_marks_achieved->>v_question_type_id)::numeric + v_marks_awarded));
    v_marks_available_map := jsonb_set(v_marks_available_map, array[v_question_type_id], to_jsonb((v_marks_available_map->>v_question_type_id)::numeric + v_marks_available));
    v_subpart_count := jsonb_set(v_subpart_count, array[v_question_type_id], to_jsonb((v_subpart_count->>v_question_type_id)::integer + 1));
    if v_status = 'correct' then
      v_correct_count := jsonb_set(v_correct_count, array[v_question_type_id], to_jsonb((v_correct_count->>v_question_type_id)::integer + 1));
    end if;

    if found and v_bank_row.content_difficulty is not null then
      v_difficulty_counts := jsonb_set(
        v_difficulty_counts, array[v_question_type_id, v_bank_row.content_difficulty::text],
        to_jsonb(((v_difficulty_counts->v_question_type_id)->>(v_bank_row.content_difficulty::text))::integer + 1)
      );
    end if;

    -- AUTHORED EDUCATIONAL EVIDENCE, safe framing only: only ever
    -- attached from an INCORRECT/unanswered row, never claims the
    -- learner exhibited it -- see this migration's own header.
    if found and v_status <> 'correct' and v_bank_row.addresses_misconception is not null then
      v_misconceptions := jsonb_set(
        v_misconceptions, array[v_question_type_id],
        (v_misconceptions->v_question_type_id) || to_jsonb(v_bank_row.addresses_misconception)
      );
    end if;

    -- competency_evidence: one provenance-tagged record per graded
    -- question, migration 074's own original design, source='mock',
    -- never fed into ali_student_question_history by this or any
    -- function.
    v_competency_evidence := v_competency_evidence || jsonb_build_object(
      'competencyId', public.mock_question_type_competency(v_question_type_id),
      'questionTypeId', v_question_type_id,
      'source', 'mock',
      'correct', (v_status = 'correct'),
      'attemptId', p_attempt_id,
      'formId', v_attempt.form_id,
      'scoredAt', now()
    );
  end loop;

  -- === Pass 2: classify each skill's evidence, build bySkill/strengths/weaknesses ===
  foreach v_skill_key in array v_skill_keys loop
    v_skill_subparts := (v_subpart_count->>v_skill_key)::integer;
    v_skill_correct := (v_correct_count->>v_skill_key)::integer;
    v_skill_achieved := (v_marks_achieved->>v_skill_key)::numeric;
    v_skill_available := (v_marks_available_map->>v_skill_key)::numeric;
    v_skill_difficulty := v_difficulty_counts->v_skill_key;
    v_skill_misconceptions := v_misconceptions->v_skill_key;

    if v_skill_available > 0 then
      v_percentage := round((v_skill_achieved / v_skill_available) * 100, 1);
    else
      v_percentage := null;
    end if;

    -- Decision 223's own disclosed, symmetric, minimum-2-observations
    -- threshold -- see this migration's own header for the full rationale.
    if v_skill_subparts < 2 then
      v_evidence_level := 'insufficient_evidence';
    elsif v_skill_correct = v_skill_subparts then
      v_evidence_level := 'demonstrated_securely';
    elsif v_skill_correct = 0 then
      v_evidence_level := 'not_yet_demonstrated';
    else
      v_evidence_level := 'developing';
    end if;

    v_by_skill := v_by_skill || jsonb_build_object(
      'questionTypeId', v_skill_key,
      'competencyId', public.mock_question_type_competency(v_skill_key),
      'marksAchieved', v_skill_achieved,
      'marksAvailable', v_skill_available,
      'percentage', v_percentage,
      'subpartCount', v_skill_subparts,
      'correctCount', v_skill_correct,
      'evidenceLevel', v_evidence_level,
      'difficultyDistribution', v_skill_difficulty,
      -- Capped at 2, never a wall of text -- see header.
      'misconceptionNotes', (select coalesce(jsonb_agg(m), '[]'::jsonb) from (select m from jsonb_array_elements_text(v_skill_misconceptions) m limit 2) sub)
    );

  end loop;

  -- === Pass 2b: roll up QT-level evidence to COMPETENCY level for
  -- strengths/weaknesses only (bySkill above stays QT-level, per
  -- Section 3's own explicit "skill/QT evidence" requirement). Several
  -- QT codes share one competency (e.g. QT-MR-01/02/03/09 all -> MR-01)
  -- -- without this rollup, a competency could appear more than once in
  -- the same strengths/weaknesses list, producing a sentence like "a
  -- real strength in: Number and Calculation, Number and Calculation."
  -- One entry per competency, re-classified at the competency's own
  -- aggregate subpart/correct count using the identical Decision-223
  -- threshold rule -- never a second, different rule. ===
  with competency_rollup as (
    select
      public.mock_question_type_competency(e->>'questionTypeId') as competency_id,
      sum((e->>'subpartCount')::integer) as subpart_count,
      sum((e->>'correctCount')::integer) as correct_count
    from jsonb_array_elements(v_by_skill) e
    group by public.mock_question_type_competency(e->>'questionTypeId')
  ),
  classified as (
    select
      competency_id, subpart_count, correct_count,
      case
        when subpart_count < 2 then 'insufficient_evidence'
        when correct_count = subpart_count then 'demonstrated_securely'
        when correct_count = 0 then 'not_yet_demonstrated'
        else 'developing'
      end as evidence_level
    from competency_rollup
    where competency_id is not null
  )
  select
    coalesce(jsonb_agg(jsonb_build_object('competencyId', competency_id, 'questionCount', subpart_count, 'correctCount', correct_count) order by competency_id) filter (where evidence_level = 'demonstrated_securely'), '[]'::jsonb),
    coalesce(jsonb_agg(jsonb_build_object('competencyId', competency_id, 'questionCount', subpart_count, 'correctCount', correct_count) order by competency_id) filter (where evidence_level in ('not_yet_demonstrated', 'developing')), '[]'::jsonb)
  into v_strengths, v_weaknesses
  from classified;

  -- === Pass 3: deterministic next-practice priorities (top 3, not_yet_demonstrated
  -- ranked before developing, then by marks lost desc, then questionTypeId asc) ===
  select coalesce(
    jsonb_agg(
      jsonb_build_object('competencyId', public.mock_question_type_competency(s.qt), 'questionTypeId', s.qt)
      order by s.rank_key, s.marks_lost desc, s.qt asc
    ),
    '[]'::jsonb
  )
  into v_priorities
  from (
    select
      (e->>'questionTypeId') as qt,
      case when (e->>'evidenceLevel') = 'not_yet_demonstrated' then 0 else 1 end as rank_key,
      ((e->>'marksAvailable')::numeric - (e->>'marksAchieved')::numeric) as marks_lost
    from jsonb_array_elements(v_by_skill) e
    where (e->>'evidenceLevel') in ('not_yet_demonstrated', 'developing')
    order by rank_key, marks_lost desc, qt asc
    limit 3
  ) s;

  update public.ali_mock_attempt_report
  set analysis_state = 'complete',
      analysis_version = v_current_analysis_version,
      analysed_at = now(),
      skill_evidence = jsonb_build_object('bySkill', v_by_skill, 'nextPracticePriorities', v_priorities),
      strengths = v_strengths,
      weaknesses = v_weaknesses,
      competency_evidence = v_competency_evidence,
      subject_breakdown = case when v_report.overall is not null then
        jsonb_build_array(jsonb_build_object(
          'subject', 'mathematics',
          'marksAchieved', (v_report.overall->>'rawMarksAchieved')::numeric,
          'marksAvailable', (v_report.overall->>'rawMarksAvailable')::numeric,
          'percentage', v_report.overall->'percentage'
        ))
      else subject_breakdown end,
      updated_at = now()
  where attempt_id = p_attempt_id;

  if not found then
    raise exception 'No report row exists for attempt % -- unexpected concurrent deletion', p_attempt_id;
  end if;
end;
$$;

-- Execute grants: granted to NO role at all, from the start -- never
-- authenticated, never anon. This function's only real caller is the
-- trigger below, inside its own SECURITY DEFINER context (the same
-- owner-implicit-privilege mechanism mock_score_attempt() already
-- relies on) -- no learner can ever call this directly, for their own
-- attempt or anyone else's.
revoke all on function public.mock_analyse_attempt(uuid) from public;

-- === Trigger function redefined: analysis runs immediately after a
-- successful score, in its own isolated exception block =================

create or replace function public.mock_attempt_report_init()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'submitted' and (old.status is distinct from 'submitted') then
    insert into public.ali_mock_attempt_report (attempt_id)
    values (new.id)
    on conflict (attempt_id) do nothing;

    begin
      perform public.mock_score_attempt(new.id);
    exception when others then
      update public.ali_mock_attempt_report
      set scoring_state = 'failed', updated_at = now()
      where attempt_id = new.id;
    end;

    -- Decision 223 -- entirely independent nested block. Only proceeds
    -- once scoring genuinely, freshly succeeded (re-read from the row,
    -- never assumed); an analysis failure here touches analysis_state
    -- only, never scoring_state/question_outcomes/overall, and can
    -- never affect the learner's own already-committed submission.
    begin
      if (select scoring_state from public.ali_mock_attempt_report where attempt_id = new.id) = 'scored' then
        perform public.mock_analyse_attempt(new.id);
      end if;
    exception when others then
      update public.ali_mock_attempt_report
      set analysis_state = 'failed', updated_at = now()
      where attempt_id = new.id;
    end;
  end if;
  return new;
end;
$$;

commit;
